import { NewsArticle, ServiceStatus } from './types';

export const MOCK_ARTICLES: NewsArticle[] = [
  // === Anthropic/Claude (5) ===
  {
    id: 'art-001',
    title: 'Anthropic Launches Claude Opus 4.5 with Native Tool Use and Extended Thinking',
    url: 'https://www.anthropic.com/news/claude-opus-4-5',
    source: 'Anthropic',
    sourceIcon: '/icons/anthropic.svg',
    sourceDomain: 'anthropic.com',
    snippet: 'Anthropic today released Claude Opus 4.5, featuring dramatically improved tool use, extended thinking chains up to 128K tokens, and a new agentic coding mode. The model is available immediately through the API and Claude.ai for Pro subscribers.',
    categories: ['Anthropic/Claude'],
    publishedAt: '2026-03-28T09:00:00Z',
    fetchedAt: '2026-03-28T09:05:00Z',
  },
  {
    id: 'art-002',
    title: 'Anthropic Introduces Claude Code General Availability with Background Agents',
    url: 'https://www.anthropic.com/news/claude-code-ga',
    source: 'Anthropic',
    sourceIcon: '/icons/anthropic.svg',
    sourceDomain: 'anthropic.com',
    snippet: 'Claude Code exits beta with background agents that can run multi-hour tasks autonomously, integrated with GitHub Actions and CI/CD pipelines. Early adopters report a 3x improvement in developer velocity on complex refactoring projects.',
    categories: ['Anthropic/Claude', 'Tools & Dev'],
    publishedAt: '2026-03-26T09:00:00Z',
    fetchedAt: '2026-03-26T09:05:00Z',
  },
  {
    id: 'art-003',
    title: 'Claude Sonnet 4.5 Tops SWE-Bench with 72% Resolve Rate',
    url: 'https://techcrunch.com/2026/03/24/claude-sonnet-4-5-swe-bench/',
    source: 'TechCrunch',
    sourceIcon: '/icons/techcrunch.svg',
    sourceDomain: 'techcrunch.com',
    snippet: 'Anthropic\'s updated Sonnet model has set a new record on the SWE-Bench Verified benchmark, resolving 72% of real-world GitHub issues autonomously. The result edges out the previous leader by nearly five percentage points.',
    categories: ['Anthropic/Claude'],
    publishedAt: '2026-03-24T14:30:00Z',
    fetchedAt: '2026-03-24T14:35:00Z',
  },
  {
    id: 'art-004',
    title: 'Anthropic Partners with Salesforce to Bring Claude into Enterprise CRM Workflows',
    url: 'https://www.bloomberg.com/news/articles/2026-03-22/anthropic-salesforce-partnership',
    source: 'Bloomberg',
    sourceIcon: '/icons/bloomberg.svg',
    sourceDomain: 'bloomberg.com',
    snippet: 'Salesforce will embed Claude as the default AI backbone for its Agentforce platform under a multi-year deal reportedly worth over $500 million. The partnership gives Anthropic a major foothold in the enterprise sales automation market.',
    categories: ['Anthropic/Claude', 'Startups'],
    publishedAt: '2026-03-22T08:00:00Z',
    fetchedAt: '2026-03-22T08:10:00Z',
  },
  {
    id: 'art-005',
    title: 'Anthropic Publishes New Research on Constitutional AI Scaling Laws',
    url: 'https://www.technologyreview.com/2026/03/18/anthropic-constitutional-ai-scaling/',
    source: 'MIT Tech Review',
    sourceIcon: '/icons/mittechreview.svg',
    sourceDomain: 'technologyreview.com',
    snippet: 'A new paper from Anthropic demonstrates that constitutional AI techniques become more effective as model scale increases. The findings suggest that alignment and capability can improve in tandem rather than trading off against each other.',
    categories: ['Anthropic/Claude', 'Policy & Safety'],
    publishedAt: '2026-03-18T11:00:00Z',
    fetchedAt: '2026-03-18T11:15:00Z',
  },

  // === OpenAI (4) ===
  {
    id: 'art-006',
    title: 'OpenAI Announces GPT-5 Turbo with Real-Time Multimodal Reasoning',
    url: 'https://openai.com/blog/gpt-5-turbo',
    source: 'OpenAI',
    sourceIcon: '/icons/openai.svg',
    sourceDomain: 'openai.com',
    snippet: 'GPT-5 Turbo delivers a 40% latency reduction over GPT-5 while maintaining benchmark performance, with native video understanding available to all API tiers. OpenAI says the model is optimized for high-throughput production workloads.',
    categories: ['OpenAI'],
    publishedAt: '2026-03-27T17:30:00Z',
    fetchedAt: '2026-03-27T17:35:00Z',
  },
  {
    id: 'art-007',
    title: 'OpenAI Rolls Out Advanced Voice Mode to Free Tier Users Worldwide',
    url: 'https://www.theverge.com/2026/3/25/openai-advanced-voice-free-tier',
    source: 'The Verge',
    sourceIcon: '/icons/theverge.svg',
    sourceDomain: 'theverge.com',
    snippet: 'Free ChatGPT users can now access the full Advanced Voice Mode including real-time translation across 40 languages. The move is widely seen as a response to growing competition from Google and Meta in the conversational AI space.',
    categories: ['OpenAI'],
    publishedAt: '2026-03-25T10:00:00Z',
    fetchedAt: '2026-03-25T10:08:00Z',
  },
  {
    id: 'art-008',
    title: 'OpenAI Launches Codex Agent for Autonomous Software Engineering',
    url: 'https://arstechnica.com/ai/2026/03/openai-codex-agent/',
    source: 'Ars Technica',
    sourceIcon: '/icons/arstechnica.svg',
    sourceDomain: 'arstechnica.com',
    snippet: 'The new Codex Agent can independently plan, implement, and test multi-file code changes inside a sandboxed environment. OpenAI claims it can handle tasks that previously required hours of developer time in under ten minutes.',
    categories: ['OpenAI', 'Tools & Dev'],
    publishedAt: '2026-03-21T15:00:00Z',
    fetchedAt: '2026-03-21T15:12:00Z',
  },
  {
    id: 'art-009',
    title: 'OpenAI and Apple Expand Partnership to Integrate GPT-5 into iOS 20',
    url: 'https://www.reuters.com/technology/openai-apple-ios20-gpt5-2026-03-19/',
    source: 'Reuters',
    sourceIcon: '/icons/reuters.svg',
    sourceDomain: 'reuters.com',
    snippet: 'Apple will deeply integrate GPT-5 across Siri, Mail, and Safari in the upcoming iOS 20 release expected this fall. The expanded deal reportedly includes on-device inference for smaller GPT variants on the A20 chip.',
    categories: ['OpenAI'],
    publishedAt: '2026-03-19T13:00:00Z',
    fetchedAt: '2026-03-19T13:10:00Z',
  },

  // === Google/Gemini (3) ===
  {
    id: 'art-010',
    title: 'Google DeepMind Unveils Gemini 2.5 Pro with 2M Token Context',
    url: 'https://blog.google/technology/ai/gemini-2-5-pro/',
    source: 'Google',
    sourceIcon: '/icons/google.svg',
    sourceDomain: 'blog.google',
    snippet: 'Gemini 2.5 Pro doubles the context window to 2 million tokens and introduces grounded code generation that cites documentation sources inline. Google says the model achieves state-of-the-art results on long-document reasoning benchmarks.',
    categories: ['Google/Gemini'],
    publishedAt: '2026-03-27T14:00:00Z',
    fetchedAt: '2026-03-27T14:10:00Z',
  },
  {
    id: 'art-011',
    title: 'Google Brings Gemini to Workspace with AI Teammates for Docs and Sheets',
    url: 'https://www.theverge.com/2026/3/23/google-gemini-workspace-ai-teammates',
    source: 'The Verge',
    sourceIcon: '/icons/theverge.svg',
    sourceDomain: 'theverge.com',
    snippet: 'Google Workspace users will soon be able to assign tasks to AI teammates powered by Gemini 2.5 that operate asynchronously on documents and spreadsheets. The feature rolls out to Enterprise customers in April before reaching all paid tiers.',
    categories: ['Google/Gemini'],
    publishedAt: '2026-03-23T09:30:00Z',
    fetchedAt: '2026-03-23T09:40:00Z',
  },
  {
    id: 'art-012',
    title: 'DeepMind AlphaFold 3.5 Predicts Protein-Drug Interactions with 95% Accuracy',
    url: 'https://www.nature.com/articles/d41586-026-00812-3',
    source: 'Nature',
    sourceIcon: '/icons/nature.svg',
    sourceDomain: 'nature.com',
    snippet: 'The latest AlphaFold model extends beyond structure prediction to accurately forecast how small-molecule drugs will bind to protein targets. Pharmaceutical partners report the tool has already shortened early-stage drug discovery timelines by months.',
    categories: ['Google/Gemini', 'Research'],
    publishedAt: '2026-03-17T16:00:00Z',
    fetchedAt: '2026-03-17T16:20:00Z',
  },

  // === Meta/Llama (3) ===
  {
    id: 'art-013',
    title: 'Meta Releases Llama 4 Scout and Maverick Open-Weight Models',
    url: 'https://ai.meta.com/blog/llama-4/',
    source: 'Meta AI',
    sourceIcon: '/icons/meta.svg',
    sourceDomain: 'ai.meta.com',
    snippet: 'Llama 4 Scout (17B active parameters, 109B total) and Maverick (17B active, 400B total) ship under a permissive license with mixture-of-experts architecture. Both models support 10 million token context and natively handle text, images, and video.',
    categories: ['Meta/Llama', 'Open Source'],
    publishedAt: '2026-03-26T18:00:00Z',
    fetchedAt: '2026-03-26T18:12:00Z',
  },
  {
    id: 'art-014',
    title: 'Meta AI Demonstrates Llama 4 Behemoth on Complex Reasoning Tasks',
    url: 'https://www.wired.com/story/meta-llama-4-behemoth-reasoning/',
    source: 'WIRED',
    sourceIcon: '/icons/wired.svg',
    sourceDomain: 'wired.com',
    snippet: 'Meta previewed its unreleased Llama 4 Behemoth model, showing it matching frontier closed-source models on math and coding benchmarks. The company says a full release of the 2-trillion-parameter model is planned for later this year.',
    categories: ['Meta/Llama'],
    publishedAt: '2026-03-24T11:00:00Z',
    fetchedAt: '2026-03-24T11:15:00Z',
  },
  {
    id: 'art-015',
    title: 'Meta Open-Sources Full Training Recipe for Llama 4 Scout',
    url: 'https://techcrunch.com/2026/03/20/meta-llama-4-training-recipe/',
    source: 'TechCrunch',
    sourceIcon: '/icons/techcrunch.svg',
    sourceDomain: 'techcrunch.com',
    snippet: 'In a first for the Llama series, Meta has published the complete training recipe including data curation pipeline and hyperparameter schedules. Researchers say the transparency will help the community reproduce and improve upon the results independently.',
    categories: ['Meta/Llama', 'Open Source'],
    publishedAt: '2026-03-20T14:00:00Z',
    fetchedAt: '2026-03-20T14:10:00Z',
  },

  // === Hardware/Chips (2) ===
  {
    id: 'art-016',
    title: 'NVIDIA Announces Blackwell Ultra B300 GPU with 288GB HBM3e',
    url: 'https://techcrunch.com/2026/03/26/nvidia-blackwell-ultra-b300/',
    source: 'TechCrunch',
    sourceIcon: '/icons/techcrunch.svg',
    sourceDomain: 'techcrunch.com',
    snippet: 'The B300 packs 288GB of HBM3e memory and delivers 2.5x inference throughput over H200, with shipments expected to hyperscalers in Q3 2026. Jensen Huang called it the most significant GPU architecture leap in five years.',
    categories: ['Hardware/Chips'],
    publishedAt: '2026-03-26T12:45:00Z',
    fetchedAt: '2026-03-26T12:50:00Z',
  },
  {
    id: 'art-017',
    title: 'AMD MI450X Challenge NVIDIA Dominance with Competitive Training Benchmarks',
    url: 'https://arstechnica.com/ai/2026/03/amd-mi450x-training-benchmarks/',
    source: 'Ars Technica',
    sourceIcon: '/icons/arstechnica.svg',
    sourceDomain: 'arstechnica.com',
    snippet: 'AMD published independent benchmarks showing its MI450X Instinct accelerators achieving 92% of NVIDIA B200 throughput on large language model training at 30% lower cost per chip. Several cloud providers have already committed to deploying MI450X clusters this summer.',
    categories: ['Hardware/Chips'],
    publishedAt: '2026-03-22T10:30:00Z',
    fetchedAt: '2026-03-22T10:40:00Z',
  },

  // === Policy & Safety (3) ===
  {
    id: 'art-018',
    title: 'EU AI Act Enforcement Begins: First Compliance Notices Issued to Foundation Model Providers',
    url: 'https://www.reuters.com/technology/eu-ai-act-enforcement-2026-03-25/',
    source: 'Reuters',
    sourceIcon: '/icons/reuters.svg',
    sourceDomain: 'reuters.com',
    snippet: 'The European AI Office issued its first formal compliance notices under the AI Act, requiring six major foundation model providers to submit transparency reports within 90 days. Companies that fail to comply face fines of up to 3% of global annual revenue.',
    categories: ['Policy & Safety'],
    publishedAt: '2026-03-25T16:20:00Z',
    fetchedAt: '2026-03-25T16:30:00Z',
  },
  {
    id: 'art-019',
    title: 'White House Executive Order Mandates AI Watermarking for Synthetic Media',
    url: 'https://www.nytimes.com/2026/03/21/technology/ai-watermarking-executive-order.html',
    source: 'New York Times',
    sourceIcon: '/icons/nyt.svg',
    sourceDomain: 'nytimes.com',
    snippet: 'A new executive order requires all AI systems generating images, audio, or video to embed C2PA-compliant provenance metadata by January 2027. Industry groups have broadly welcomed the standard while noting the tight implementation timeline.',
    categories: ['Policy & Safety'],
    publishedAt: '2026-03-21T20:00:00Z',
    fetchedAt: '2026-03-21T20:15:00Z',
  },
  {
    id: 'art-020',
    title: 'California Passes Landmark Bill Requiring Safety Evaluations for Frontier AI Models',
    url: 'https://www.bloomberg.com/news/articles/2026-03-16/california-ai-safety-bill',
    source: 'Bloomberg',
    sourceIcon: '/icons/bloomberg.svg',
    sourceDomain: 'bloomberg.com',
    snippet: 'The bill mandates independent pre-deployment safety evaluations for any AI model trained with more than 10^26 FLOPS of compute. Governor Newsom signed the legislation after months of negotiation between lawmakers and major AI labs.',
    categories: ['Policy & Safety'],
    publishedAt: '2026-03-16T19:00:00Z',
    fetchedAt: '2026-03-16T19:10:00Z',
  },

  // === Open Source (3) ===
  {
    id: 'art-021',
    title: 'Mistral Releases Codestral Mamba 2 for Long-Context Code Generation',
    url: 'https://mistral.ai/news/codestral-mamba-2/',
    source: 'Mistral AI',
    sourceIcon: '/icons/mistral.svg',
    sourceDomain: 'mistral.ai',
    snippet: 'Codestral Mamba 2 uses a state-space architecture to handle unlimited context length at linear cost, outperforming transformer baselines on repository-level code tasks. The model weights are released under the Apache 2.0 license.',
    categories: ['Open Source', 'Tools & Dev'],
    publishedAt: '2026-03-25T13:00:00Z',
    fetchedAt: '2026-03-25T13:15:00Z',
  },
  {
    id: 'art-022',
    title: 'Hugging Face Launches Open Leaderboard v3 with Agent Benchmarks',
    url: 'https://huggingface.co/blog/open-leaderboard-v3',
    source: 'Hugging Face',
    sourceIcon: '/icons/huggingface.svg',
    sourceDomain: 'huggingface.co',
    snippet: 'The new leaderboard adds agentic task completion, tool-use accuracy, and multi-step reasoning benchmarks alongside traditional NLP evaluations. Over 200 open-weight models have already been submitted for ranking in the first week.',
    categories: ['Open Source', 'Tools & Dev'],
    publishedAt: '2026-03-23T15:00:00Z',
    fetchedAt: '2026-03-23T15:10:00Z',
  },
  {
    id: 'art-023',
    title: 'EleutherAI Ships GPT-NeoX 30B v2 with Fully Reproducible Training Pipeline',
    url: 'https://www.technologyreview.com/2026/03/19/eleutherai-neox-30b-v2/',
    source: 'MIT Tech Review',
    sourceIcon: '/icons/mittechreview.svg',
    sourceDomain: 'technologyreview.com',
    snippet: 'The open research collective released a 30-billion parameter model alongside every artifact needed to reproduce training from scratch. The effort is part of a broader push to make frontier model development accessible to academic labs.',
    categories: ['Open Source', 'Research'],
    publishedAt: '2026-03-19T10:00:00Z',
    fetchedAt: '2026-03-19T10:12:00Z',
  },

  // === Startups/Tools (3) ===
  {
    id: 'art-024',
    title: 'Cursor Raises $900M at $9B Valuation to Build the AI-Native IDE',
    url: 'https://www.theinformation.com/articles/cursor-raises-900m',
    source: 'The Information',
    sourceIcon: '/icons/theinformation.svg',
    sourceDomain: 'theinformation.com',
    snippet: 'AI code editor Cursor has raised a $900M Series C led by Thrive Capital, nearly tripling its valuation from six months ago as developer adoption surges past 5 million. The company plans to use the funds to expand its enterprise offering and hire aggressively.',
    categories: ['Startups', 'Tools & Dev'],
    publishedAt: '2026-03-25T11:00:00Z',
    fetchedAt: '2026-03-25T11:08:00Z',
  },
  {
    id: 'art-025',
    title: 'Perplexity AI Launches Enterprise Search with Private Data Connectors',
    url: 'https://techcrunch.com/2026/03/23/perplexity-enterprise-search/',
    source: 'TechCrunch',
    sourceIcon: '/icons/techcrunch.svg',
    sourceDomain: 'techcrunch.com',
    snippet: 'Perplexity now lets enterprise customers connect internal knowledge bases, Confluence wikis, and Slack channels to its AI search engine. The company says Fortune 500 clients can get answers grounded in both public and private data within seconds.',
    categories: ['Startups', 'Tools & Dev'],
    publishedAt: '2026-03-23T12:00:00Z',
    fetchedAt: '2026-03-23T12:08:00Z',
  },
  {
    id: 'art-026',
    title: 'Replit Launches Agent 2.0 That Can Deploy Full-Stack Apps from a Single Prompt',
    url: 'https://www.wired.com/story/replit-agent-2-deploy-apps-prompt/',
    source: 'WIRED',
    sourceIcon: '/icons/wired.svg',
    sourceDomain: 'wired.com',
    snippet: 'Replit Agent 2.0 can scaffold, code, test, and deploy complete web applications including database setup and authentication flows. The company reports that over 100,000 production apps have been built using the agent since its quiet launch last month.',
    categories: ['Startups', 'Tools & Dev'],
    publishedAt: '2026-03-18T14:00:00Z',
    fetchedAt: '2026-03-18T14:10:00Z',
  },

  // === Research (2) ===
  {
    id: 'art-027',
    title: 'Stanford Researchers Propose "Inference Scaling Laws" for Chain-of-Thought Models',
    url: 'https://arxiv.org/abs/2026.14523',
    source: 'arXiv',
    sourceIcon: '/icons/arxiv.svg',
    sourceDomain: 'arxiv.org',
    snippet: 'A new paper from Stanford HAI formalizes how increasing compute at inference time yields predictable performance gains for reasoning-heavy tasks. The findings have significant implications for how companies allocate resources between training and serving.',
    categories: ['Research'],
    publishedAt: '2026-03-20T08:00:00Z',
    fetchedAt: '2026-03-20T08:20:00Z',
  },
  {
    id: 'art-028',
    title: 'MIT CSAIL Demonstrates Sparse Mixture-of-Experts at 10x Training Efficiency',
    url: 'https://www.technologyreview.com/2026/03/15/mit-sparse-moe-efficiency/',
    source: 'MIT Tech Review',
    sourceIcon: '/icons/mittechreview.svg',
    sourceDomain: 'technologyreview.com',
    snippet: 'Researchers at MIT CSAIL achieved a 10x reduction in training compute by using an adaptive sparse routing mechanism that activates only 5% of model parameters per token. The technique could make training large models feasible on university-scale hardware budgets.',
    categories: ['Research'],
    publishedAt: '2026-03-15T12:00:00Z',
    fetchedAt: '2026-03-15T12:15:00Z',
  },

  // === Community/HN (2) ===
  {
    id: 'art-029',
    title: 'Show HN: I Built a Local-First AI Coding Assistant That Runs Entirely on Apple Silicon',
    url: 'https://news.ycombinator.com/item?id=42891234',
    source: 'Hacker News',
    sourceIcon: '/icons/hackernews.svg',
    sourceDomain: 'news.ycombinator.com',
    snippet: 'A solo developer built a VS Code extension that runs a quantized 14B coding model entirely on-device using Metal acceleration, with no cloud dependency. The project hit the top of Hacker News and has already gained over 4,000 GitHub stars in two days.',
    categories: ['Community', 'Tools & Dev'],
    publishedAt: '2026-03-27T06:00:00Z',
    fetchedAt: '2026-03-27T06:15:00Z',
  },
  {
    id: 'art-030',
    title: 'The Great AI Bubble Debate: HN Weighs In on Whether Foundation Model Startups Are Overvalued',
    url: 'https://news.ycombinator.com/item?id=42887654',
    source: 'Hacker News',
    sourceIcon: '/icons/hackernews.svg',
    sourceDomain: 'news.ycombinator.com',
    snippet: 'A heated thread on Hacker News analyzing the unit economics of AI startups has drawn over 1,200 comments in 24 hours. Contributors range from VC partners defending current valuations to engineers arguing that commoditization is inevitable.',
    categories: ['Community'],
    publishedAt: '2026-03-16T22:00:00Z',
    fetchedAt: '2026-03-16T22:10:00Z',
  },
];

export const MOCK_STATUSES: ServiceStatus[] = [
  {
    name: 'Claude API',
    provider: 'Anthropic',
    status: 'operational',
    uptime7d: 99.98,
    lastIncident: null,
    components: [
      { name: 'Messages API', status: 'operational' },
      { name: 'Batches API', status: 'operational' },
      { name: 'Tool Use', status: 'operational' },
    ],
    statusPageUrl: 'https://status.anthropic.com',
  },
  {
    name: 'ChatGPT / OpenAI API',
    provider: 'OpenAI',
    status: 'operational',
    uptime7d: 99.91,
    lastIncident: '2026-03-25T04:12:00Z',
    components: [
      { name: 'Chat Completions', status: 'operational' },
      { name: 'Assistants API', status: 'operational' },
      { name: 'Image Generation', status: 'operational' },
    ],
    statusPageUrl: 'https://status.openai.com',
  },
  {
    name: 'Gemini API',
    provider: 'Google',
    status: 'degraded',
    uptime7d: 98.74,
    lastIncident: '2026-03-28T06:45:00Z',
    components: [
      { name: 'GenerateContent', status: 'degraded' },
      { name: 'Embeddings', status: 'operational' },
      { name: 'Grounding', status: 'operational' },
    ],
    statusPageUrl: 'https://status.cloud.google.com',
  },
  {
    name: 'Azure OpenAI',
    provider: 'Microsoft',
    status: 'operational',
    uptime7d: 99.95,
    lastIncident: '2026-03-20T11:30:00Z',
    components: [
      { name: 'Inference (East US)', status: 'operational' },
      { name: 'Inference (West Europe)', status: 'operational' },
      { name: 'Fine-tuning', status: 'operational' },
    ],
    statusPageUrl: 'https://status.azure.com',
  },
  {
    name: 'AWS Bedrock',
    provider: 'Amazon',
    status: 'operational',
    uptime7d: 99.99,
    lastIncident: null,
    components: [
      { name: 'Model Inference', status: 'operational' },
      { name: 'Knowledge Bases', status: 'operational' },
      { name: 'Agents', status: 'operational' },
    ],
    statusPageUrl: 'https://health.aws.amazon.com',
  },
  {
    name: 'Mistral Platform',
    provider: 'Mistral AI',
    status: 'operational',
    uptime7d: 99.87,
    lastIncident: '2026-03-22T09:00:00Z',
    components: [
      { name: 'Chat API', status: 'operational' },
      { name: 'Embeddings', status: 'operational' },
    ],
    statusPageUrl: 'https://status.mistral.ai',
  },
  {
    name: 'Replicate',
    provider: 'Replicate',
    status: 'operational',
    uptime7d: 99.82,
    lastIncident: '2026-03-23T14:20:00Z',
    components: [
      { name: 'Predictions API', status: 'operational' },
      { name: 'Deployments', status: 'operational' },
    ],
    statusPageUrl: 'https://status.replicate.com',
  },
  {
    name: 'Hugging Face Inference',
    provider: 'Hugging Face',
    status: 'degraded',
    uptime7d: 99.12,
    lastIncident: '2026-03-28T03:20:00Z',
    components: [
      { name: 'Inference Endpoints', status: 'operational' },
      { name: 'Serverless API', status: 'degraded' },
      { name: 'Spaces', status: 'operational' },
    ],
    statusPageUrl: 'https://status.huggingface.co',
  },
  {
    name: 'Cohere API',
    provider: 'Cohere',
    status: 'down',
    uptime7d: 97.45,
    lastIncident: '2026-03-28T07:30:00Z',
    components: [
      { name: 'Chat', status: 'down' },
      { name: 'Embed', status: 'down' },
      { name: 'Rerank', status: 'operational' },
    ],
    statusPageUrl: 'https://status.cohere.com',
  },
  {
    name: 'Groq Cloud',
    provider: 'Groq',
    status: 'operational',
    uptime7d: 99.93,
    lastIncident: '2026-03-19T22:10:00Z',
    components: [
      { name: 'LPU Inference', status: 'operational' },
      { name: 'API Gateway', status: 'operational' },
    ],
    statusPageUrl: 'https://status.groq.com',
  },
  {
    name: 'Perplexity API',
    provider: 'Perplexity',
    status: 'operational',
    uptime7d: 99.89,
    lastIncident: '2026-03-21T15:45:00Z',
    components: [
      { name: 'Sonar API', status: 'operational' },
      { name: 'Online Search', status: 'operational' },
    ],
    statusPageUrl: 'https://status.perplexity.ai',
  },
  {
    name: 'Together AI',
    provider: 'Together AI',
    status: 'operational',
    uptime7d: 99.78,
    lastIncident: '2026-03-24T08:30:00Z',
    components: [
      { name: 'Inference API', status: 'operational' },
      { name: 'Fine-tuning', status: 'operational' },
      { name: 'Custom Models', status: 'operational' },
    ],
    statusPageUrl: 'https://status.together.ai',
  },
];
