import { NewsArticle, ServiceStatus } from './types';

export const MOCK_ARTICLES: NewsArticle[] = [
  {
    id: 'art-001',
    title: 'Anthropic Launches Claude Opus 4.5 with Native Tool Use and Extended Thinking',
    url: 'https://www.anthropic.com/news/claude-opus-4-5',
    source: 'Anthropic',
    sourceIcon: '/icons/anthropic.svg',
    sourceDomain: 'anthropic.com',
    snippet: 'Anthropic today released Claude Opus 4.5, featuring dramatically improved tool use, extended thinking chains up to 128K tokens, and a new agentic coding mode.',
    categories: ['Anthropic/Claude'],
    publishedAt: '2026-03-28T09:00:00Z',
    fetchedAt: '2026-03-28T09:05:00Z',
  },
  {
    id: 'art-002',
    title: 'OpenAI Announces GPT-5 Turbo with Real-Time Multimodal Reasoning',
    url: 'https://openai.com/blog/gpt-5-turbo',
    source: 'OpenAI',
    sourceIcon: '/icons/openai.svg',
    sourceDomain: 'openai.com',
    snippet: 'GPT-5 Turbo delivers a 40% latency reduction over GPT-5 while maintaining benchmark performance, with native video understanding available to all API tiers.',
    categories: ['OpenAI'],
    publishedAt: '2026-03-27T17:30:00Z',
    fetchedAt: '2026-03-27T17:35:00Z',
  },
  {
    id: 'art-003',
    title: 'Google DeepMind Unveils Gemini 2.5 Pro with 2M Token Context',
    url: 'https://blog.google/technology/ai/gemini-2-5-pro/',
    source: 'Google',
    sourceIcon: '/icons/google.svg',
    sourceDomain: 'blog.google',
    snippet: 'Gemini 2.5 Pro doubles the context window to 2 million tokens and introduces grounded code generation that cites documentation sources inline.',
    categories: ['Google/Gemini'],
    publishedAt: '2026-03-27T14:00:00Z',
    fetchedAt: '2026-03-27T14:10:00Z',
  },
  {
    id: 'art-004',
    title: 'Meta Releases Llama 4 Scout and Maverick Open-Weight Models',
    url: 'https://ai.meta.com/blog/llama-4/',
    source: 'Meta AI',
    sourceIcon: '/icons/meta.svg',
    sourceDomain: 'ai.meta.com',
    snippet: 'Llama 4 Scout (17B active parameters, 109B total) and Maverick (17B active, 400B total) ship under a permissive license with mixture-of-experts architecture.',
    categories: ['Meta/Llama', 'Open Source'],
    publishedAt: '2026-03-26T18:00:00Z',
    fetchedAt: '2026-03-26T18:12:00Z',
  },
  {
    id: 'art-005',
    title: 'NVIDIA Announces Blackwell Ultra B300 GPU with 288GB HBM3e',
    url: 'https://techcrunch.com/2026/03/26/nvidia-blackwell-ultra-b300/',
    source: 'TechCrunch',
    sourceIcon: '/icons/techcrunch.svg',
    sourceDomain: 'techcrunch.com',
    snippet: 'The B300 packs 288GB of HBM3e memory and delivers 2.5x inference throughput over H200, with shipments expected to hyperscalers in Q3 2026.',
    categories: ['Hardware/Chips'],
    publishedAt: '2026-03-26T12:45:00Z',
    fetchedAt: '2026-03-26T12:50:00Z',
  },
  {
    id: 'art-006',
    title: 'EU AI Act Enforcement Begins: First Compliance Notices Issued to Foundation Model Providers',
    url: 'https://www.reuters.com/technology/eu-ai-act-enforcement-2026-03-25/',
    source: 'Reuters',
    sourceIcon: '/icons/reuters.svg',
    sourceDomain: 'reuters.com',
    snippet: 'The European AI Office issued its first formal compliance notices under the AI Act, requiring six major foundation model providers to submit transparency reports within 90 days.',
    categories: ['Policy & Safety'],
    publishedAt: '2026-03-25T16:20:00Z',
    fetchedAt: '2026-03-25T16:30:00Z',
  },
  {
    id: 'art-007',
    title: 'Cursor Raises $900M at $9B Valuation to Build the AI-Native IDE',
    url: 'https://www.theinformation.com/articles/cursor-raises-900m',
    source: 'The Information',
    sourceIcon: '/icons/theinformation.svg',
    sourceDomain: 'theinformation.com',
    snippet: 'AI code editor Cursor has raised a $900M Series C led by Thrive Capital, nearly tripling its valuation from six months ago as developer adoption surges past 5 million.',
    categories: ['Startups', 'Tools & Dev'],
    publishedAt: '2026-03-25T11:00:00Z',
    fetchedAt: '2026-03-25T11:08:00Z',
  },
  {
    id: 'art-008',
    title: 'Mistral Releases Codestral Mamba 2 for Long-Context Code Generation',
    url: 'https://mistral.ai/news/codestral-mamba-2/',
    source: 'Mistral AI',
    sourceIcon: '/icons/mistral.svg',
    sourceDomain: 'mistral.ai',
    snippet: 'Codestral Mamba 2 uses a state-space architecture to handle unlimited context length at linear cost, outperforming transformer baselines on repository-level code tasks.',
    categories: ['Open Source', 'Tools & Dev'],
    publishedAt: '2026-03-24T13:00:00Z',
    fetchedAt: '2026-03-24T13:15:00Z',
  },
  {
    id: 'art-009',
    title: 'Anthropic Introduces Claude Code General Availability with Background Agents',
    url: 'https://www.anthropic.com/news/claude-code-ga',
    source: 'Anthropic',
    sourceIcon: '/icons/anthropic.svg',
    sourceDomain: 'anthropic.com',
    snippet: 'Claude Code exits beta with background agents that can run multi-hour tasks autonomously, integrated with GitHub Actions and CI/CD pipelines.',
    categories: ['Anthropic/Claude', 'Tools & Dev'],
    publishedAt: '2026-03-24T09:00:00Z',
    fetchedAt: '2026-03-24T09:05:00Z',
  },
  {
    id: 'art-010',
    title: 'Hugging Face Launches Open Leaderboard v3 with Agent Benchmarks',
    url: 'https://huggingface.co/blog/open-leaderboard-v3',
    source: 'Hugging Face',
    sourceIcon: '/icons/huggingface.svg',
    sourceDomain: 'huggingface.co',
    snippet: 'The new leaderboard adds agentic task completion, tool-use accuracy, and multi-step reasoning benchmarks alongside traditional NLP evaluations.',
    categories: ['Open Source', 'Tools & Dev'],
    publishedAt: '2026-03-23T15:00:00Z',
    fetchedAt: '2026-03-23T15:10:00Z',
  },
  {
    id: 'art-011',
    title: 'xAI Deploys 200,000 GPU Colossus v2 Cluster in Memphis',
    url: 'https://www.wired.com/story/xai-colossus-v2-memphis/',
    source: 'WIRED',
    sourceIcon: '/icons/wired.svg',
    sourceDomain: 'wired.com',
    snippet: 'Elon Musk\'s xAI has completed its expanded Memphis data center with 200,000 NVIDIA H200 GPUs, making it the largest known single-site AI training cluster.',
    categories: ['Hardware/Chips', 'Startups'],
    publishedAt: '2026-03-22T10:30:00Z',
    fetchedAt: '2026-03-22T10:40:00Z',
  },
  {
    id: 'art-012',
    title: 'White House Executive Order Mandates AI Watermarking for Synthetic Media',
    url: 'https://www.nytimes.com/2026/03/21/technology/ai-watermarking-executive-order.html',
    source: 'New York Times',
    sourceIcon: '/icons/nyt.svg',
    sourceDomain: 'nytimes.com',
    snippet: 'A new executive order requires all AI systems generating images, audio, or video to embed C2PA-compliant provenance metadata by January 2027.',
    categories: ['Policy & Safety'],
    publishedAt: '2026-03-21T20:00:00Z',
    fetchedAt: '2026-03-21T20:15:00Z',
  },
];

export const MOCK_STATUSES: ServiceStatus[] = [
  {
    name: 'Claude API',
    provider: 'Anthropic',
    status: 'operational',
    uptime7d: 99.98,
    lastIncident: null,
    components: [
      { name: 'Messages API', status: 'operational' },
      { name: 'Batches API', status: 'operational' },
      { name: 'Tool Use', status: 'operational' },
    ],
    statusPageUrl: 'https://status.anthropic.com',
  },
  {
    name: 'ChatGPT / OpenAI API',
    provider: 'OpenAI',
    status: 'operational',
    uptime7d: 99.91,
    lastIncident: '2026-03-25T04:12:00Z',
    components: [
      { name: 'Chat Completions', status: 'operational' },
      { name: 'Assistants API', status: 'operational' },
      { name: 'Image Generation', status: 'operational' },
    ],
    statusPageUrl: 'https://status.openai.com',
  },
  {
    name: 'Gemini API',
    provider: 'Google',
    status: 'degraded',
    uptime7d: 98.74,
    lastIncident: '2026-03-28T06:45:00Z',
    components: [
      { name: 'GenerateContent', status: 'degraded' },
      { name: 'Embeddings', status: 'operational' },
      { name: 'Grounding', status: 'operational' },
    ],
    statusPageUrl: 'https://status.cloud.google.com',
  },
  {
    name: 'Azure OpenAI',
    provider: 'Microsoft',
    status: 'operational',
    uptime7d: 99.95,
    lastIncident: '2026-03-20T11:30:00Z',
    components: [
      { name: 'Inference (East US)', status: 'operational' },
      { name: 'Inference (West Europe)', status: 'operational' },
      { name: 'Fine-tuning', status: 'operational' },
    ],
    statusPageUrl: 'https://status.azure.com',
  },
  {
    name: 'AWS Bedrock',
    provider: 'Amazon',
    status: 'operational',
    uptime7d: 99.99,
    lastIncident: null,
    components: [
      { name: 'Model Inference', status: 'operational' },
      { name: 'Knowledge Bases', status: 'operational' },
      { name: 'Agents', status: 'operational' },
    ],
    statusPageUrl: 'https://health.aws.amazon.com',
  },
  {
    name: 'Mistral Platform',
    provider: 'Mistral AI',
    status: 'operational',
    uptime7d: 99.87,
    lastIncident: '2026-03-22T09:00:00Z',
    components: [
      { name: 'Chat API', status: 'operational' },
      { name: 'Embeddings', status: 'operational' },
    ],
    statusPageUrl: 'https://status.mistral.ai',
  },
  {
    name: 'Replicate',
    provider: 'Replicate',
    status: 'operational',
    uptime7d: 99.82,
    lastIncident: '2026-03-23T14:20:00Z',
    components: [
      { name: 'Predictions API', status: 'operational' },
      { name: 'Deployments', status: 'operational' },
    ],
    statusPageUrl: 'https://status.replicate.com',
  },
  {
    name: 'Hugging Face Inference',
    provider: 'Hugging Face',
    status: 'operational',
    uptime7d: 99.76,
    lastIncident: '2026-03-24T17:45:00Z',
    components: [
      { name: 'Inference Endpoints', status: 'operational' },
      { name: 'Serverless API', status: 'operational' },
      { name: 'Spaces', status: 'operational' },
    ],
    statusPageUrl: 'https://status.huggingface.co',
  },
  {
    name: 'Cohere API',
    provider: 'Cohere',
    status: 'down',
    uptime7d: 97.45,
    lastIncident: '2026-03-28T07:30:00Z',
    components: [
      { name: 'Chat', status: 'down' },
      { name: 'Embed', status: 'down' },
      { name: 'Rerank', status: 'operational' },
    ],
    statusPageUrl: 'https://status.cohere.com',
  },
  {
    name: 'Groq Cloud',
    provider: 'Groq',
    status: 'operational',
    uptime7d: 99.93,
    lastIncident: '2026-03-19T22:10:00Z',
    components: [
      { name: 'LPU Inference', status: 'operational' },
      { name: 'API Gateway', status: 'operational' },
    ],
    statusPageUrl: 'https://status.groq.com',
  },
];
