/**
 * Chaos engineering headers for agent developer experience.
 *
 * Lets agent devs deliberately trigger failure modes against TensorFeed
 * so they can test their fallback logic (router, retries, backoff,
 * graceful degradation) without waiting for a real upstream incident.
 *
 * Both headers are no-auth, work on every endpoint, and never charge
 * credits. Simulated errors short-circuit the worker before the route
 * dispatch and before requirePayment, so a CI test that hammers
 * `X-TensorFeed-Simulate-Error: 503` against a premium endpoint is free.
 *
 * Headers
 * -------
 *   X-TensorFeed-Simulate-Error: <status_code>
 *     Returns the requested status code immediately. Accepts 4xx and
 *     5xx. Anything outside [400, 599] is rejected as 400.
 *
 *   X-TensorFeed-Simulate-Latency: <ms>
 *     Sleeps the requested number of milliseconds before letting the
 *     request continue. Capped at MAX_LATENCY_MS to protect the worker
 *     from DoS via header. Negative or non-numeric values are ignored.
 *
 * Both responses include `X-TensorFeed-Simulated: true` so callers can
 * verify the response came from the chaos layer and not the real
 * upstream.
 */

const ERROR_HEADER = 'X-TensorFeed-Simulate-Error';
const LATENCY_HEADER = 'X-TensorFeed-Simulate-Latency';
const SIMULATED_FLAG_HEADER = 'X-TensorFeed-Simulated';

const MIN_ERROR_CODE = 400;
const MAX_ERROR_CODE = 599;
const MAX_LATENCY_MS = 10_000;

const DEFAULT_CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, X-Payment-Tx, X-TensorFeed-Simulate-Error, X-TensorFeed-Simulate-Latency',
};

interface ChaosErrorBody {
  ok: false;
  error: 'simulated_error';
  status: number;
  message: string;
  simulated: true;
  hint: string;
}

/**
 * If `X-TensorFeed-Simulate-Error` is present, return a Response with
 * the requested status code. The body declares the response is
 * simulated so an agent's logging/alerting cannot mistake it for a
 * real outage.
 *
 * Returns null when the header is absent so the caller can fall
 * through to normal request handling.
 */
export function maybeSimulatedErrorResponse(request: Request): Response | null {
  const raw = request.headers.get(ERROR_HEADER);
  if (!raw) return null;

  const parsed = parseInt(raw, 10);
  if (Number.isNaN(parsed) || parsed < MIN_ERROR_CODE || parsed > MAX_ERROR_CODE) {
    const body: ChaosErrorBody = {
      ok: false,
      error: 'simulated_error',
      status: 400,
      message: `Invalid status code in ${ERROR_HEADER}. Must be an integer in [${MIN_ERROR_CODE}, ${MAX_ERROR_CODE}].`,
      simulated: true,
      hint: 'Try X-TensorFeed-Simulate-Error: 503 to simulate Service Unavailable.',
    };
    return new Response(JSON.stringify(body), {
      status: 400,
      headers: {
        ...DEFAULT_CORS,
        'Content-Type': 'application/json',
        [SIMULATED_FLAG_HEADER]: 'true',
      },
    });
  }

  const body: ChaosErrorBody = {
    ok: false,
    error: 'simulated_error',
    status: parsed,
    message: simulatedMessageFor(parsed),
    simulated: true,
    hint: 'This response was generated by the TensorFeed chaos engineering layer because the request included an X-TensorFeed-Simulate-Error header. No upstream call was made and no credits were charged.',
  };
  return new Response(JSON.stringify(body), {
    status: parsed,
    headers: {
      ...DEFAULT_CORS,
      'Content-Type': 'application/json',
      [SIMULATED_FLAG_HEADER]: 'true',
    },
  });
}

/**
 * If `X-TensorFeed-Simulate-Latency` is present, await the requested
 * delay (capped) before resolving. Caller can `await applySimulatedLatency(request)`
 * unconditionally; it's a fast no-op when the header is absent.
 *
 * Returns the actual ms slept (0 when the header is missing or invalid)
 * so callers can append it to their response logging if desired.
 */
export async function applySimulatedLatency(request: Request): Promise<number> {
  const raw = request.headers.get(LATENCY_HEADER);
  if (!raw) return 0;

  const parsed = parseInt(raw, 10);
  if (Number.isNaN(parsed) || parsed <= 0) return 0;
  const ms = Math.min(parsed, MAX_LATENCY_MS);
  await new Promise<void>((resolve) => setTimeout(resolve, ms));
  return ms;
}

/**
 * Inject the simulated flag header into an arbitrary response so the
 * latency simulation is observable to the caller. Callers should run
 * this only when latency was actually applied.
 */
export function tagSimulatedLatency(response: Response, ms: number): Response {
  if (ms <= 0) return response;
  const newHeaders = new Headers(response.headers);
  newHeaders.set(SIMULATED_FLAG_HEADER, 'true');
  newHeaders.set('X-TensorFeed-Simulated-Latency-Ms', String(ms));
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers: newHeaders,
  });
}

function simulatedMessageFor(status: number): string {
  if (status === 503) return 'Simulated Service Unavailable. Test your fallback path now.';
  if (status === 504) return 'Simulated Gateway Timeout.';
  if (status === 502) return 'Simulated Bad Gateway.';
  if (status === 500) return 'Simulated Internal Server Error.';
  if (status === 429) return 'Simulated rate limit exceeded.';
  if (status === 408) return 'Simulated Request Timeout.';
  if (status === 401) return 'Simulated Unauthorized.';
  if (status === 403) return 'Simulated Forbidden.';
  if (status === 404) return 'Simulated Not Found.';
  return `Simulated HTTP ${status}.`;
}

export const CHAOS_LIMITS = {
  MAX_LATENCY_MS,
  MIN_ERROR_CODE,
  MAX_ERROR_CODE,
};

// ── Simulated-response counter ────────────────────────────────────────
//
// Tracks how many simulated responses the chaos layer has handed back,
// bucketed by status code. Powers /api/chaos/stats and lets external
// analytics (traffic-tracker) subtract synthetic traffic from real 5xx
// rates so the dashboard doesn't show 14% errors when the actual error
// rate is well under 1%.
//
// Mirrors the activity.ts pattern: increment in-memory on every hit,
// flush to KV in batches to stay well inside the free-tier KV budget.
// Counter is per-UTC-day. Reset happens implicitly when the date rolls
// over and the next flush sees a stale `date` field.

interface ChaosCounter {
  date: string; // YYYY-MM-DD UTC
  total: number;
  by_status: Record<string, number>;
}

const COUNTER_KEY = 'chaos:counter';
const FLUSH_INTERVAL_MS = 60_000;
const FLUSH_BATCH_SIZE = 20;
const READ_CACHE_TTL_MS = 30_000;

let pendingByStatus = new Map<number, number>();
let pendingTotal = 0;
let lastFlushTime = 0;

let cachedStats: { data: ChaosCounter; expiresAt: number } | null = null;

function todayUTC(): string {
  return new Date().toISOString().slice(0, 10);
}

function emptyCounter(): ChaosCounter {
  return { date: todayUTC(), total: 0, by_status: {} };
}

/**
 * Synchronously record a simulated response. No env required, no KV
 * write on the hot path. Caller should follow with maybeFlushChaos so
 * the buffer eventually lands in KV.
 */
export function noteSimulatedResponse(status: number): void {
  pendingByStatus.set(status, (pendingByStatus.get(status) ?? 0) + 1);
  pendingTotal++;
}

/**
 * Flush the in-memory counter to KV when the batch size or interval
 * threshold is reached. Safe to call on every request: it's a no-op
 * when nothing is pending or the threshold hasn't been hit. Caller is
 * responsible for wrapping in ctx.waitUntil if they want fire-and-forget.
 */
export async function maybeFlushChaos(env: { TENSORFEED_CACHE: KVNamespace }): Promise<void> {
  if (pendingTotal === 0) return;
  const now = Date.now();
  if (pendingTotal < FLUSH_BATCH_SIZE && now - lastFlushTime < FLUSH_INTERVAL_MS) return;
  await flushChaosToKV(env);
}

async function flushChaosToKV(env: { TENSORFEED_CACHE: KVNamespace }): Promise<void> {
  if (pendingTotal === 0) return;

  const drainedByStatus = new Map(pendingByStatus);
  const drainedTotal = pendingTotal;
  pendingByStatus.clear();
  pendingTotal = 0;
  lastFlushTime = Date.now();

  try {
    const today = todayUTC();
    const stored = (await env.TENSORFEED_CACHE.get(COUNTER_KEY, 'json')) as ChaosCounter | null;
    const counter: ChaosCounter = stored && stored.date === today ? stored : emptyCounter();
    counter.total += drainedTotal;
    for (const [status, n] of drainedByStatus) {
      const k = String(status);
      counter.by_status[k] = (counter.by_status[k] ?? 0) + n;
    }
    await env.TENSORFEED_CACHE.put(COUNTER_KEY, JSON.stringify(counter));
    cachedStats = null;
  } catch (err) {
    console.warn('chaos counter flush failed:', err);
    // Re-add so we don't lose counts on transient KV errors
    for (const [status, n] of drainedByStatus) {
      pendingByStatus.set(status, (pendingByStatus.get(status) ?? 0) + n);
    }
    pendingTotal += drainedTotal;
  }
}

/**
 * Read the current counter snapshot, including any in-memory pending
 * counts that haven't flushed yet. Caches the KV read for 30 seconds.
 */
export async function getChaosStats(env: { TENSORFEED_CACHE: KVNamespace }): Promise<ChaosCounter> {
  const now = Date.now();
  const today = todayUTC();

  let base: ChaosCounter;
  if (cachedStats && now < cachedStats.expiresAt && cachedStats.data.date === today) {
    base = cachedStats.data;
  } else {
    const stored = (await env.TENSORFEED_CACHE.get(COUNTER_KEY, 'json')) as ChaosCounter | null;
    base = stored && stored.date === today ? stored : emptyCounter();
    cachedStats = { data: base, expiresAt: now + READ_CACHE_TTL_MS };
  }

  if (pendingTotal === 0) return base;

  const merged: ChaosCounter = {
    date: base.date,
    total: base.total + pendingTotal,
    by_status: { ...base.by_status },
  };
  for (const [status, n] of pendingByStatus) {
    const k = String(status);
    merged.by_status[k] = (merged.by_status[k] ?? 0) + n;
  }
  return merged;
}

/**
 * Test-only reset. Wipes both the in-memory buffer and the cached read
 * snapshot. Vitest tests share module state across cases otherwise.
 */
export function _resetChaosCounterForTests(): void {
  pendingByStatus = new Map();
  pendingTotal = 0;
  lastFlushTime = 0;
  cachedStats = null;
}
