/**
 * AI funding rounds tracker.
 *
 * Notable AI startup financing rounds with structured fields: date,
 * stage, amount, post-money valuation, lead investors, what the company
 * does. Different from /api/news which covers funding news as
 * unstructured text. This is the machine-readable layer.
 *
 * Editorial; refreshed on redeploy when notable rounds close.
 *
 * Served at /api/funding (free, cached 600s).
 */

export interface FundingRound {
  id: string;
  company: string;
  category: 'frontier-lab' | 'inference' | 'agent' | 'coding' | 'infra' | 'enterprise' | 'creative' | 'voice' | 'video' | 'data' | 'safety';
  /** Round stage. */
  stage: 'seed' | 'series-a' | 'series-b' | 'series-c' | 'series-d' | 'series-e' | 'series-f' | 'growth' | 'tender' | 'debt' | 'strategic';
  /** Amount raised in USD millions. */
  amountM: number;
  /** Post-money valuation in USD billions. Null if undisclosed or pre-money / debt. */
  valuationB: number | null;
  /** Round announcement date (YYYY-MM-DD). */
  announcedDate: string;
  /** Lead investor(s). */
  leadInvestors: string[];
  /** Notable participants beyond lead. */
  notableInvestors: string[];
  /** Sector/products. */
  description: string;
  /** Company URL. */
  url: string;
  /** Source URL for the announcement. */
  sourceUrl: string;
}

export const FUNDING_ROUNDS: FundingRound[] = [
  // ── 2026 ────────────────────────────────────────────
  {
    id: 'anthropic-google-2026-04',
    company: 'Anthropic',
    category: 'frontier-lab',
    stage: 'strategic',
    amountM: 40000,
    valuationB: 350,
    announcedDate: '2026-04-21',
    leadInvestors: ['Google'],
    notableInvestors: [],
    description: '10-year compute commitment from Google for TPU access. Not a traditional equity round; Google deepens its dual-track AI strategy.',
    url: 'https://www.anthropic.com',
    sourceUrl: 'https://www.anthropic.com/news/google-anthropic-compute-commitment',
  },
  {
    id: 'cursor-2026-q1',
    company: 'Anysphere (Cursor)',
    category: 'coding',
    stage: 'series-c',
    amountM: 900,
    valuationB: 9.0,
    announcedDate: '2026-02-12',
    leadInvestors: ['Thrive Capital', 'Andreessen Horowitz'],
    notableInvestors: ['Accel', 'OpenAI Startup Fund'],
    description: 'AI-native code editor; largest paid install base of any AI IDE. Round triples valuation in 6 months.',
    url: 'https://cursor.com',
    sourceUrl: 'https://www.cursor.com/blog/series-c',
  },
  {
    id: 'cognition-2026-q1',
    company: 'Cognition Labs',
    category: 'coding',
    stage: 'series-b',
    amountM: 500,
    valuationB: 4.0,
    announcedDate: '2026-01-30',
    leadInvestors: ['Founders Fund'],
    notableInvestors: ['8VC', 'Khosla Ventures'],
    description: 'Builder of Devin (autonomous SWE agent) + DeepWiki retrieval. Round pays for compute scale-up.',
    url: 'https://devin.ai',
    sourceUrl: 'https://www.cognition.ai',
  },
  {
    id: 'mistral-2026-q1',
    company: 'Mistral AI',
    category: 'frontier-lab',
    stage: 'series-c',
    amountM: 1500,
    valuationB: 12.0,
    announcedDate: '2026-03-04',
    leadInvestors: ['Salesforce Ventures', 'General Catalyst'],
    notableInvestors: ['Andreessen Horowitz', 'Lightspeed', 'Bpifrance'],
    description: 'European frontier-model lab. Round pegged to la Plateforme + Codestral commercial growth.',
    url: 'https://mistral.ai',
    sourceUrl: 'https://mistral.ai/news/series-c-funding',
  },
  {
    id: 'sierra-2026-q1',
    company: 'Sierra',
    category: 'agent',
    stage: 'series-c',
    amountM: 350,
    valuationB: 4.5,
    announcedDate: '2026-03-18',
    leadInvestors: ['Greenoaks Capital'],
    notableInvestors: ['Sequoia Capital', 'Benchmark', 'Thrive Capital'],
    description: 'Conversational AI for customer support. Founded by Bret Taylor. Tau-Bench creators.',
    url: 'https://sierra.ai',
    sourceUrl: 'https://sierra.ai/blog',
  },
  {
    id: 'decagon-2026-q1',
    company: 'Decagon',
    category: 'agent',
    stage: 'series-c',
    amountM: 250,
    valuationB: 2.0,
    announcedDate: '2026-02-04',
    leadInvestors: ['BOND'],
    notableInvestors: ['Andreessen Horowitz', 'Accel'],
    description: 'AI customer-service agents for enterprise. Counts Eventbrite, Notion, ClassPass as customers.',
    url: 'https://decagon.ai',
    sourceUrl: 'https://decagon.ai/blog',
  },
  {
    id: 'glean-2026-q1',
    company: 'Glean',
    category: 'enterprise',
    stage: 'series-f',
    amountM: 260,
    valuationB: 7.2,
    announcedDate: '2026-01-15',
    leadInvestors: ['Altimeter Capital', 'DST Global'],
    notableInvestors: ['Coatue', 'Sequoia Capital'],
    description: 'Enterprise search + AI assistant. Round signals continued enterprise-AI expansion in 2026.',
    url: 'https://www.glean.com',
    sourceUrl: 'https://www.glean.com/blog/series-f',
  },
  // ── 2025 ────────────────────────────────────────────
  {
    id: 'openai-2025-10',
    company: 'OpenAI',
    category: 'frontier-lab',
    stage: 'tender',
    amountM: 6600,
    valuationB: 157,
    announcedDate: '2025-10-02',
    leadInvestors: ['Thrive Capital'],
    notableInvestors: ['Microsoft', 'NVIDIA', 'SoftBank', 'Khosla Ventures'],
    description: 'Tender offer at $157B post-money. Largest private round in tech history at time of close.',
    url: 'https://openai.com',
    sourceUrl: 'https://openai.com/index/scale-the-benefits-of-ai/',
  },
  {
    id: 'anthropic-2025-08',
    company: 'Anthropic',
    category: 'frontier-lab',
    stage: 'series-f',
    amountM: 4500,
    valuationB: 60,
    announcedDate: '2025-08-12',
    leadInvestors: ['Lightspeed Venture Partners'],
    notableInvestors: ['Google', 'Salesforce Ventures', 'Bessemer Venture Partners'],
    description: 'Series F at $60B post. Pre-dates the $40B Google compute commitment in April 2026.',
    url: 'https://www.anthropic.com',
    sourceUrl: 'https://www.anthropic.com/news/series-f',
  },
  {
    id: 'perplexity-2025-12',
    company: 'Perplexity',
    category: 'agent',
    stage: 'series-d',
    amountM: 500,
    valuationB: 9.0,
    announcedDate: '2025-12-08',
    leadInvestors: ['IVP'],
    notableInvestors: ['Andreessen Horowitz', 'NEA', 'NVIDIA'],
    description: 'Answer engine. Round funds product expansion (Comet browser, Pages, finance tools).',
    url: 'https://www.perplexity.ai',
    sourceUrl: 'https://www.perplexity.ai/blog/series-d',
  },
  {
    id: 'cohere-2025-q3',
    company: 'Cohere',
    category: 'frontier-lab',
    stage: 'series-d',
    amountM: 500,
    valuationB: 5.5,
    announcedDate: '2025-08-22',
    leadInvestors: ['PSP Investments', 'Cisco'],
    notableInvestors: ['NVIDIA', 'AMD', 'Salesforce Ventures'],
    description: 'Enterprise RAG-focused frontier lab. Round positions Cohere as the enterprise AI alternative.',
    url: 'https://cohere.com',
    sourceUrl: 'https://cohere.com/blog/series-d',
  },
  {
    id: 'groq-2025-q1',
    company: 'Groq',
    category: 'inference',
    stage: 'series-d',
    amountM: 640,
    valuationB: 2.8,
    announcedDate: '2025-08-05',
    leadInvestors: ['BlackRock'],
    notableInvestors: ['Cisco', 'Samsung Catalyst Fund'],
    description: 'Custom LPU silicon for ultra-fast inference. Round funds capacity expansion + Saudi Arabia data center.',
    url: 'https://groq.com',
    sourceUrl: 'https://groq.com/news_press/groq-raises-640-million-series-d',
  },
  {
    id: 'together-2025-q1',
    company: 'Together AI',
    category: 'inference',
    stage: 'series-b',
    amountM: 305,
    valuationB: 3.3,
    announcedDate: '2025-02-20',
    leadInvestors: ['General Catalyst', 'Prosperity7 Ventures'],
    notableInvestors: ['Salesforce Ventures', 'NVIDIA', 'Lux Capital'],
    description: 'Inference + fine-tuning hosting for open-weights models. Round funds GPU capacity expansion.',
    url: 'https://www.together.ai',
    sourceUrl: 'https://www.together.ai/blog/series-b',
  },
  {
    id: 'sakana-2025-q1',
    company: 'Sakana AI',
    category: 'frontier-lab',
    stage: 'series-a',
    amountM: 200,
    valuationB: 1.5,
    announcedDate: '2025-09-10',
    leadInvestors: ['NVIDIA'],
    notableInvestors: ['Khosla Ventures', 'Lux Capital'],
    description: 'Tokyo-based research lab. Evolutionary model-merging research. The largest non-US, non-China AI seed of 2025.',
    url: 'https://sakana.ai',
    sourceUrl: 'https://sakana.ai/series-a/',
  },
  {
    id: 'harvey-2025-q1',
    company: 'Harvey',
    category: 'enterprise',
    stage: 'series-d',
    amountM: 300,
    valuationB: 3.0,
    announcedDate: '2025-07-23',
    leadInvestors: ['GV (Google Ventures)'],
    notableInvestors: ['OpenAI Startup Fund', 'Sequoia', 'Conviction'],
    description: 'AI for legal work. Round funds expansion beyond AmLaw 100 to mid-market firms.',
    url: 'https://www.harvey.ai',
    sourceUrl: 'https://www.harvey.ai/blog/series-d',
  },
  {
    id: 'crusoe-2025-q1',
    company: 'Crusoe',
    category: 'infra',
    stage: 'series-d',
    amountM: 600,
    valuationB: 2.8,
    announcedDate: '2025-06-04',
    leadInvestors: ['Founders Fund'],
    notableInvestors: ['Mubadala', 'Fidelity', 'NVIDIA'],
    description: 'AI-first data center operator. Builds GPU clusters powered by stranded methane / clean energy.',
    url: 'https://crusoe.ai',
    sourceUrl: 'https://crusoe.ai/blog/series-d',
  },
  {
    id: 'elevenlabs-2025-q1',
    company: 'ElevenLabs',
    category: 'voice',
    stage: 'series-c',
    amountM: 250,
    valuationB: 3.3,
    announcedDate: '2025-01-30',
    leadInvestors: ['Andreessen Horowitz', 'ICONIQ Growth'],
    notableInvestors: ['NEA', 'Sequoia'],
    description: 'Voice AI. Round funds expansion into agents (conversational AI) and enterprise voice cloning.',
    url: 'https://elevenlabs.io',
    sourceUrl: 'https://elevenlabs.io/blog/series-c-funding',
  },
  {
    id: 'cartesia-2025-q1',
    company: 'Cartesia',
    category: 'voice',
    stage: 'series-a',
    amountM: 64,
    valuationB: 0.4,
    announcedDate: '2025-03-17',
    leadInvestors: ['Kleiner Perkins'],
    notableInvestors: ['Lightspeed', 'Index Ventures', 'A* Capital'],
    description: 'Mamba-architecture TTS. Sub-90ms TTFB. Round funds team scale-up + voice agent platform.',
    url: 'https://cartesia.ai',
    sourceUrl: 'https://cartesia.ai/blog/series-a',
  },
  {
    id: 'glean-2025-q3',
    company: 'Glean',
    category: 'enterprise',
    stage: 'series-e',
    amountM: 260,
    valuationB: 4.6,
    announcedDate: '2025-09-10',
    leadInvestors: ['DST Global', 'Altimeter'],
    notableInvestors: ['Coatue', 'General Catalyst'],
    description: 'Enterprise search + AI assistant. Series E pre-dates the 2026 series F at $7.2B.',
    url: 'https://www.glean.com',
    sourceUrl: 'https://www.glean.com/blog/series-e',
  },
  // ── Earlier reference points ────────────────────────
  {
    id: 'xai-2024-12',
    company: 'xAI',
    category: 'frontier-lab',
    stage: 'series-c',
    amountM: 6000,
    valuationB: 50,
    announcedDate: '2024-12-23',
    leadInvestors: ['Andreessen Horowitz', 'Sequoia Capital', 'Valor Equity Partners'],
    notableInvestors: ['NVIDIA', 'AMD', 'Fidelity', 'Kingdom Holding Co'],
    description: 'Elon Musk\'s frontier lab. Funded the Memphis 200k-GPU Colossus cluster.',
    url: 'https://x.ai',
    sourceUrl: 'https://x.ai/news/series-c',
  },
  {
    id: 'openai-2024-10',
    company: 'OpenAI',
    category: 'frontier-lab',
    stage: 'series-c',
    amountM: 6600,
    valuationB: 157,
    announcedDate: '2024-10-02',
    leadInvestors: ['Thrive Capital'],
    notableInvestors: ['Microsoft', 'NVIDIA', 'Khosla Ventures', 'SoftBank'],
    description: '$6.6B round at $157B post. Largest private round in tech history at the time.',
    url: 'https://openai.com',
    sourceUrl: 'https://openai.com/index/scale-the-benefits-of-ai/',
  },
];

export const FUNDING_LAST_UPDATED = '2026-04-30';
