/**
 * Storefront-coverage drift guard.
 *
 * premium-catalog.test.ts proves catalog <-> handler parity. It does NOT
 * prove that a payable endpoint is actually advertised on the x402 storefront
 * (public/.well-known/x402.json) that agentic.market, the Coinbase CDP Bazaar
 * crawler, and x402scan ingest. Those crawlers are how a paying agent finds an
 * endpoint without being told its URL, so a catalog entry missing from the
 * manifest is invisible to crawler-driven demand even though it serves a valid
 * 402 when hit directly.
 *
 * That exact gap shipped silently: nine payable endpoints (model-intelligence,
 * substrate-changelog/history, the funding/procurement/policy family, and
 * ai-datacenters/buildout) were in the catalog and emitting live 402s but were
 * never registered as Bazaar pilots, so they never reached the manifest. This
 * suite asserts every PREMIUM_CATALOG path is represented by a manifest item,
 * so the storefront can no longer drift behind the catalog without CI failing.
 *
 * The manifest is regenerated by scripts/sync-x402-manifest.ts during prebuild.
 * If this test fails after you add a premium endpoint, you most likely:
 *   1. added the catalog row + handler but no Bazaar pilot
 *      (register one in worker/src/bazaar-pilots.ts + PILOT_METADATA), or
 *   2. registered the pilot but did not regenerate the committed manifest
 *      (run: npx tsx scripts/sync-x402-manifest.ts).
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { describe, it, expect } from 'vitest';
import { PREMIUM_CATALOG } from './premium-catalog';

const HERE = dirname(fileURLToPath(import.meta.url));
const MANIFEST_PATH = join(HERE, '..', '..', 'public', '.well-known', 'x402.json');

interface ManifestResource {
  url?: string;
}
interface ManifestItem {
  resource: string | ManifestResource;
}
interface Manifest {
  items: ManifestItem[];
}

function manifestPathnames(): string[] {
  const raw = readFileSync(MANIFEST_PATH, 'utf8');
  const manifest = JSON.parse(raw) as Manifest;
  const out: string[] = [];
  for (const item of manifest.items) {
    const url = typeof item.resource === 'string' ? item.resource : item.resource?.url;
    if (!url) continue;
    try {
      out.push(new URL(url).pathname);
    } catch {
      out.push(url);
    }
  }
  return out;
}

/**
 * A catalog path may carry {param} segments (e.g.
 * /api/premium/clean/cve/{cve_id}). It is covered when at least one manifest
 * pathname matches it with each {param} treated as a single-segment wildcard.
 * That folds three manifest shapes into one match:
 *   - exact flat paths (no params),
 *   - template items the sync emits for :param pilots (the wildcard matches
 *     the literal :id segment),
 *   - concrete BlockRun-style split instances (the wildcard matches the value).
 */
function catalogPathToRegex(catalogPath: string): RegExp {
  const pattern = catalogPath
    .split('/')
    .map((seg) => (/^\{[^}]+\}$/.test(seg) ? '[^/]+' : seg.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
    .join('/');
  return new RegExp(`^${pattern}$`);
}

describe('premium catalog is fully published on the x402 storefront', () => {
  const manifestPaths = manifestPathnames();

  it('every PREMIUM_CATALOG path is represented by a manifest item', () => {
    const uncovered: string[] = [];
    for (const entry of PREMIUM_CATALOG) {
      const re = catalogPathToRegex(entry.path);
      if (!manifestPaths.some((p) => re.test(p))) {
        uncovered.push(entry.path);
      }
    }
    expect(
      uncovered,
      `These payable catalog endpoints are absent from public/.well-known/x402.json, ` +
        `so crawler-driven agents cannot discover them. Register each as a Bazaar pilot ` +
        `in bazaar-pilots.ts + PILOT_METADATA and regenerate the manifest ` +
        `(npx tsx scripts/sync-x402-manifest.ts):\n  ${uncovered.join('\n  ')}`,
    ).toEqual([]);
  });

  it('manifest items all advertise x402 V2 on Base mainnet USDC', () => {
    // Light structural guard so a regenerated manifest cannot silently ship a
    // non-V2 or wrong-network accepts entry alongside the new coverage.
    const raw = readFileSync(MANIFEST_PATH, 'utf8');
    const manifest = JSON.parse(raw) as {
      items: Array<{ x402Version?: number; accepts?: Array<{ network?: string; scheme?: string }> }>;
    };
    const bad: string[] = [];
    for (const item of manifest.items) {
      const a = item.accepts?.[0];
      if (item.x402Version !== 2) bad.push('x402Version!=2');
      if (a?.network !== 'eip155:8453') bad.push(`network=${a?.network}`);
      if (a?.scheme !== 'exact') bad.push(`scheme=${a?.scheme}`);
    }
    expect(bad).toEqual([]);
  });
});
