import { RSSSource } from './types';

export const RSS_SOURCES: RSSSource[] = [
  {
    id: 'google-ai',
    name: 'Google AI Blog',
    url: 'https://blog.google/technology/ai/rss/',
    domain: 'blog.google',
    categories: ['Google/Gemini'],
    active: true,
  },
  {
    id: 'huggingface',
    name: 'Hugging Face Blog',
    url: 'https://huggingface.co/blog/feed.xml',
    domain: 'huggingface.co',
    categories: ['Open Source', 'Models'],
    active: true,
  },
  {
    id: 'techcrunch-ai',
    name: 'TechCrunch AI',
    url: 'https://techcrunch.com/tag/artificial-intelligence/feed/',
    domain: 'techcrunch.com',
    categories: ['General AI'],
    active: true,
  },
  {
    id: 'verge-ai',
    name: 'The Verge AI',
    url: 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml',
    domain: 'theverge.com',
    categories: ['General AI'],
    active: true,
  },
  {
    id: 'ars-technica',
    name: 'Ars Technica',
    url: 'https://feeds.arstechnica.com/arstechnica/technology-lab',
    domain: 'arstechnica.com',
    categories: ['General AI'],
    active: true,
  },
  {
    id: 'venturebeat',
    name: 'VentureBeat AI',
    url: 'https://venturebeat.com/category/ai/feed/',
    domain: 'venturebeat.com',
    categories: ['Startups', 'Enterprise'],
    active: true,
  },
  {
    id: 'mit-tech-review',
    name: 'MIT Technology Review',
    url: 'https://www.technologyreview.com/feed/',
    domain: 'technologyreview.com',
    categories: ['Research', 'Policy & Safety'],
    active: true,
  },
  {
    id: 'nvidia-ai',
    name: 'NVIDIA AI Blog',
    url: 'https://blogs.nvidia.com/feed/',
    domain: 'blogs.nvidia.com',
    categories: ['Hardware/Chips'],
    active: true,
  },
  {
    id: 'arxiv-ai',
    name: 'arXiv cs.AI',
    url: 'https://rss.arxiv.org/rss/cs.AI',
    domain: 'arxiv.org',
    categories: ['Research'],
    active: true,
  },
  {
    id: 'hackernews-ai',
    name: 'Hacker News AI',
    url: 'https://hnrss.org/newest?q=AI+OR+LLM+OR+GPT+OR+Claude',
    domain: 'news.ycombinator.com',
    categories: ['Community'],
    active: true,
  },
  {
    id: 'wired-ai',
    name: 'WIRED AI',
    url: 'https://www.wired.com/feed/tag/ai/latest/rss',
    domain: 'wired.com',
    categories: ['General AI'],
    active: true,
  },
  {
    id: 'zdnet-ai',
    name: 'ZDNet AI',
    url: 'https://www.zdnet.com/topic/artificial-intelligence/rss.xml',
    domain: 'zdnet.com',
    categories: ['Enterprise', 'General AI'],
    active: true,
  },
];

export const STATUS_PAGES: { name: string; provider: string; url: string; statusPageUrl: string }[] = [
  {
    name: 'Claude API',
    provider: 'Anthropic',
    url: 'https://status.anthropic.com/api/v2/summary.json',
    statusPageUrl: 'https://status.anthropic.com',
  },
  {
    name: 'OpenAI API',
    provider: 'OpenAI',
    url: 'https://status.openai.com/api/v2/summary.json',
    statusPageUrl: 'https://status.openai.com',
  },
  {
    name: 'Hugging Face',
    provider: 'Hugging Face',
    url: 'https://status.huggingface.co/api/v2/summary.json',
    statusPageUrl: 'https://status.huggingface.co',
  },
  {
    name: 'Replicate',
    provider: 'Replicate',
    url: 'https://status.replicate.com/api/v2/summary.json',
    statusPageUrl: 'https://status.replicate.com',
  },
  {
    name: 'Cohere',
    provider: 'Cohere',
    url: 'https://status.cohere.com/api/v2/summary.json',
    statusPageUrl: 'https://status.cohere.com',
  },
  {
    name: 'Mistral',
    provider: 'Mistral AI',
    url: 'https://status.mistral.ai/api/v2/summary.json',
    statusPageUrl: 'https://status.mistral.ai',
  },
];
