/**
 * TerminalFeed AI-crypto pulse fetcher.
 *
 * Second AFTA federation cross-call. Pulls TerminalFeed's two crypto
 * surfaces in parallel and filters each to TF's curated AI-thesis token
 * cohort.
 *
 *   GET https://terminalfeed.io/api/crypto-movers
 *       -> { data: [{ name, symbol, price_usd, change_24h_percent, market_cap }] }
 *   GET https://terminalfeed.io/api/funding-rates
 *       -> { data: { top: [{ venue, symbol, periodHours, periodRate,
 *                              annualizedPct, markPrice }],
 *                    failed_venues: [] } }
 *
 * Both endpoints are public free on TerminalFeed. Lazy KV refresh with
 * a 5-minute TTL on the snapshot (faster cadence than ai-velocity
 * because crypto markets move fast and the upstreams already poll at
 * 30s/60s, so 5-min cache loses one fresh data-point at worst).
 *
 * Free   /api/ai-crypto-pulse                Capped + raw cohort
 * Paid   /api/premium/ai-crypto-pulse (1c)   Derived squeeze/chase + skew
 */

import type { Env } from './types';

const TERMINALFEED_MOVERS_URL = 'https://terminalfeed.io/api/crypto-movers';
const TERMINALFEED_FUNDING_URL = 'https://terminalfeed.io/api/funding-rates';
const POLITE_UA = 'tensorfeed-federation/1.0 (mailto:evan@tensorfeed.ai; +https://tensorfeed.ai)';
const FETCH_TIMEOUT_MS = 10_000;

export const TF_CRYPTO_CURRENT_KEY = 'tf-ai-crypto:current';
export const TF_CRYPTO_TTL_SECONDS = 5 * 60;

// ── AI-thesis token cohort (curated) ───────────────────────────────
//
// Conservative list. Every entry is a token with a public, on-record AI
// thesis (compute marketplace, agent economy, AI training/data, etc.).
// Symbol matching is uppercase exact-match to avoid false hits like
// AI-prefixed memecoins.
export const AI_CRYPTO_COHORT: ReadonlyArray<{
  symbol: string;
  display_name: string;
  thesis: string;
}> = [
  { symbol: 'TAO', display_name: 'Bittensor', thesis: 'decentralized ML training network' },
  { symbol: 'FET', display_name: 'Fetch.ai', thesis: 'autonomous agent economy' },
  { symbol: 'RNDR', display_name: 'Render', thesis: 'decentralized GPU render network' },
  { symbol: 'AKT', display_name: 'Akash', thesis: 'decentralized GPU compute marketplace' },
  { symbol: 'AGIX', display_name: 'SingularityNET', thesis: 'decentralized AI services marketplace' },
  { symbol: 'WLD', display_name: 'Worldcoin', thesis: 'proof-of-humanity for the AI era' },
  { symbol: 'IO', display_name: 'io.net', thesis: 'decentralized GPU compute' },
  { symbol: 'ARKM', display_name: 'Arkham Intelligence', thesis: 'on-chain intelligence platform' },
  { symbol: 'OCEAN', display_name: 'Ocean Protocol', thesis: 'data marketplace for AI training' },
  { symbol: 'GRT', display_name: 'The Graph', thesis: 'data indexing layer used by AI dapps' },
  { symbol: 'VIRTUAL', display_name: 'Virtual Protocol', thesis: 'tokenized AI agents' },
  { symbol: 'AI16Z', display_name: 'ai16z', thesis: 'AI-managed DAO + agent framework (Eliza)' },
  { symbol: 'NMR', display_name: 'Numeraire', thesis: 'crowdsourced ML hedge fund' },
  { symbol: 'TURBO', display_name: 'TurboToadz', thesis: 'memecoin generated by GPT-4 (often cohort-included for narrative)' },
];

const COHORT_SYMBOLS: ReadonlySet<string> = new Set(AI_CRYPTO_COHORT.map((c) => c.symbol));

// ── Upstream shapes ────────────────────────────────────────────────

interface UpstreamCryptoMover {
  name?: string;
  symbol?: string;
  price_usd?: number;
  change_24h_percent?: number;
  market_cap?: number;
}

interface UpstreamMoversResponse {
  data?: UpstreamCryptoMover[];
}

interface UpstreamFundingEntry {
  venue?: string;
  symbol?: string;
  periodHours?: number;
  periodRate?: number;
  annualizedPct?: number;
  markPrice?: number;
}

interface UpstreamFundingResponse {
  data?: {
    top?: UpstreamFundingEntry[];
    failed_venues?: string[];
  };
}

// ── Normalized shapes ──────────────────────────────────────────────

export interface CryptoMoverEntry {
  symbol: string;
  display_name: string;
  thesis: string;
  upstream_name: string;
  price_usd: number;
  change_24h_percent: number;
  market_cap: number;
}

export interface FundingEntry {
  symbol: string;
  display_name: string;
  thesis: string;
  venue: string;
  upstream_symbol: string;
  period_hours: number;
  period_rate: number;
  annualized_pct: number;
  mark_price: number;
}

export interface AiCryptoSnapshot {
  capturedAt: string;
  source: 'terminalfeed.io';
  upstream_endpoints: { movers: string; funding: string };
  source_license: 'Federation cross-call to TerminalFeed (free public endpoints). Upstream crypto market data carries the upstream provider\'s own terms.';
  movers_cohort_size: number;
  movers_total_upstream: number;
  funding_cohort_size: number;
  funding_total_upstream: number;
  failed_venues: string[];
  movers: CryptoMoverEntry[];
  funding: FundingEntry[];
  /**
   * True when exactly one upstream surface (movers OR funding) returned
   * zero rows on this poll. The premium handler routes a degraded snapshot
   * to a no-charge response so an agent never pays full price for a
   * squeeze/chase join that is missing an entire side. Absent / false
   * means both surfaces had data (or both were empty, handled as an
   * upstream failure upstream of this flag).
   */
  degraded?: boolean;
  /** Which surface(s) were empty when degraded. e.g. ['funding'] or ['movers']. */
  partial_sources?: string[];
}

// ── Helpers ────────────────────────────────────────────────────────

/**
 * Normalize a crypto symbol from upstream. Strips perp suffixes like
 * "TAOUSDT", "TAO-PERP", "TAO/USDT", returning the base symbol. Returns
 * the input uppercased when no perp pattern matches.
 */
export function normalizeSymbol(raw: string): string {
  if (!raw) return '';
  let s = raw.toUpperCase().trim();
  // Strip stable-pair suffixes (USDT, USDC, USD, USDT-PERP, USDC-PERP, etc.)
  s = s.replace(/[-_\/]?(PERP|SWAP)$/i, '');
  s = s.replace(/[-_\/]?(USDT|USDC|USD|BUSD|DAI)$/i, '');
  return s;
}

export function inCohort(symbol: string): boolean {
  return COHORT_SYMBOLS.has(symbol);
}

function cohortMeta(symbol: string): { display_name: string; thesis: string } | null {
  const entry = AI_CRYPTO_COHORT.find((c) => c.symbol === symbol);
  return entry ? { display_name: entry.display_name, thesis: entry.thesis } : null;
}

export function normalizeMover(e: UpstreamCryptoMover): CryptoMoverEntry | null {
  if (!e.symbol || typeof e.symbol !== 'string') return null;
  const sym = normalizeSymbol(e.symbol);
  if (!inCohort(sym)) return null;
  const meta = cohortMeta(sym);
  if (!meta) return null;
  return {
    symbol: sym,
    display_name: meta.display_name,
    thesis: meta.thesis,
    upstream_name: typeof e.name === 'string' ? e.name : meta.display_name,
    price_usd: typeof e.price_usd === 'number' ? e.price_usd : 0,
    change_24h_percent: typeof e.change_24h_percent === 'number' ? e.change_24h_percent : 0,
    market_cap: typeof e.market_cap === 'number' ? e.market_cap : 0,
  };
}

export function normalizeFunding(e: UpstreamFundingEntry): FundingEntry | null {
  if (!e.symbol || typeof e.symbol !== 'string') return null;
  const sym = normalizeSymbol(e.symbol);
  if (!inCohort(sym)) return null;
  const meta = cohortMeta(sym);
  if (!meta) return null;
  return {
    symbol: sym,
    display_name: meta.display_name,
    thesis: meta.thesis,
    venue: typeof e.venue === 'string' ? e.venue : '',
    upstream_symbol: e.symbol,
    period_hours: typeof e.periodHours === 'number' ? e.periodHours : 8,
    period_rate: typeof e.periodRate === 'number' ? e.periodRate : 0,
    annualized_pct: typeof e.annualizedPct === 'number' ? e.annualizedPct : 0,
    mark_price: typeof e.markPrice === 'number' ? e.markPrice : 0,
  };
}

// ── Fetch ──────────────────────────────────────────────────────────

async function fetchWithTimeout(url: string, init: RequestInit, ms = FETCH_TIMEOUT_MS): Promise<Response> {
  const controller = new AbortController();
  const id = setTimeout(() => controller.abort(), ms);
  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(id);
  }
}

async function fetchMovers(): Promise<{ cohort: CryptoMoverEntry[]; total: number }> {
  try {
    const res = await fetchWithTimeout(TERMINALFEED_MOVERS_URL, {
      headers: { 'User-Agent': POLITE_UA, Accept: 'application/json' },
    });
    if (!res.ok) return { cohort: [], total: 0 };
    const body = (await res.json()) as UpstreamMoversResponse;
    const all = body.data ?? [];
    const cohort: CryptoMoverEntry[] = [];
    for (const e of all) {
      const n = normalizeMover(e);
      if (n) cohort.push(n);
    }
    return { cohort, total: all.length };
  } catch {
    return { cohort: [], total: 0 };
  }
}

async function fetchFunding(): Promise<{ cohort: FundingEntry[]; total: number; failed_venues: string[] }> {
  try {
    const res = await fetchWithTimeout(TERMINALFEED_FUNDING_URL, {
      headers: { 'User-Agent': POLITE_UA, Accept: 'application/json' },
    });
    if (!res.ok) return { cohort: [], total: 0, failed_venues: [] };
    const body = (await res.json()) as UpstreamFundingResponse;
    const all = body.data?.top ?? [];
    const cohort: FundingEntry[] = [];
    for (const e of all) {
      const n = normalizeFunding(e);
      if (n) cohort.push(n);
    }
    return { cohort, total: all.length, failed_venues: body.data?.failed_venues ?? [] };
  } catch {
    return { cohort: [], total: 0, failed_venues: [] };
  }
}

/** Result shape from the two crypto upstream fetches, for the pure builder. */
export interface MoversFetchResult { cohort: CryptoMoverEntry[]; total: number }
export interface FundingFetchResult { cohort: FundingEntry[]; total: number; failed_venues: string[] }

/**
 * Detect a single-source (partial) crypto fetch. A surface is considered
 * down when its upstream returned zero rows (total === 0). Returns the
 * list of empty surfaces only when EXACTLY one is empty; [] when both
 * have data and [] when both are empty (full outage, handled separately).
 * Pure + tested.
 */
export function detectPartialCryptoSources(movers: MoversFetchResult, funding: FundingFetchResult): string[] {
  const moversEmpty = movers.total === 0;
  const fundingEmpty = funding.total === 0;
  if (moversEmpty === fundingEmpty) return []; // both empty or both full: not partial
  return moversEmpty ? ['movers'] : ['funding'];
}

/**
 * Build the snapshot to persist + serve on a crypto refresh. On a partial
 * fetch (exactly one surface empty) the empty surface is back-filled from
 * the last-known-good cached snapshot so a transient single-source blip
 * does not destroy the good cached data, and the snapshot is marked
 * degraded so the premium handler can no-charge. Pure + tested. `now` is
 * injectable for deterministic tests.
 */
export function buildCryptoSnapshot(
  movers: MoversFetchResult,
  funding: FundingFetchResult,
  cached: AiCryptoSnapshot | null,
  now: Date = new Date(),
): AiCryptoSnapshot {
  const partial = detectPartialCryptoSources(movers, funding);

  let moversCohort = movers.cohort;
  let moversTotal = movers.total;
  let fundingCohort = funding.cohort;
  let fundingTotal = funding.total;
  let failedVenues = funding.failed_venues;
  if (partial.includes('movers') && cached) {
    moversCohort = cached.movers ?? [];
    moversTotal = cached.movers_total_upstream ?? moversCohort.length;
  }
  if (partial.includes('funding') && cached) {
    fundingCohort = cached.funding ?? [];
    fundingTotal = cached.funding_total_upstream ?? fundingCohort.length;
    failedVenues = cached.failed_venues ?? failedVenues;
  }

  const snapshot: AiCryptoSnapshot = {
    capturedAt: now.toISOString(),
    source: 'terminalfeed.io',
    upstream_endpoints: { movers: TERMINALFEED_MOVERS_URL, funding: TERMINALFEED_FUNDING_URL },
    source_license: 'Federation cross-call to TerminalFeed (free public endpoints). Upstream crypto market data carries the upstream provider\'s own terms.',
    movers_cohort_size: moversCohort.length,
    movers_total_upstream: moversTotal,
    funding_cohort_size: fundingCohort.length,
    funding_total_upstream: fundingTotal,
    failed_venues: failedVenues,
    movers: moversCohort,
    funding: fundingCohort,
  };
  if (partial.length > 0) {
    snapshot.degraded = true;
    snapshot.partial_sources = partial;
  }
  return snapshot;
}

/**
 * Lazy refresh entry. Same pattern as `terminalfeed-ai-velocity-fetcher`:
 * read cached snapshot, return if fresh enough, else fetch both upstreams
 * in parallel and write a new snapshot with backup TTL.
 *
 * Partial-fetch handling (audit 2026-05-31 #13/#14): when exactly one
 * surface returns zero rows (single-source outage), the empty surface is
 * preserved from the last-known-good snapshot instead of overwriting it,
 * and the snapshot is flagged `degraded` so the premium handler no-charges.
 */
export async function getOrRefreshCryptoSnapshot(env: Env): Promise<AiCryptoSnapshot | null> {
  const cached = (await env.TENSORFEED_CACHE.get(TF_CRYPTO_CURRENT_KEY, 'json')) as AiCryptoSnapshot | null;
  const now = Date.now();
  if (cached) {
    const age = (now - new Date(cached.capturedAt).getTime()) / 1000;
    if (age < TF_CRYPTO_TTL_SECONDS) return cached;
  }

  const [movers, funding] = await Promise.all([fetchMovers(), fetchFunding()]);
  if (movers.total === 0 && funding.total === 0) {
    return cached;
  }

  const partial = detectPartialCryptoSources(movers, funding);
  if (partial.length > 0 && cached) {
    // Single-source outage and we hold a prior snapshot: keep serving the
    // last-known-good full snapshot rather than poisoning the cache with a
    // half-empty poll for the backup-TTL window. Skip the KV write to
    // preserve the good snapshot and avoid a hot-path write on the
    // degraded path; freshness SLA covers any staleness.
    return cached;
  }

  const snapshot = buildCryptoSnapshot(movers, funding, cached, new Date());
  // 30-min backup TTL so a brief TerminalFeed hiccup still serves last
  // known good. Premium freshness SLA on the consuming endpoint clamps
  // billable staleness so abusing the backup doesn't burn agent credits.
  await env.TENSORFEED_CACHE.put(TF_CRYPTO_CURRENT_KEY, JSON.stringify(snapshot), {
    expirationTtl: 30 * 60,
  });
  return snapshot;
}
