import { MetadataRoute } from 'next';
import { getAllModelSlugs } from '@/lib/model-directory';
import { getAllComparisonSlugs } from '@/lib/comparison-directory';
import { getAllProviderSlugs } from '@/lib/provider-directory';
import { getAllBenchmarkSlugs } from '@/lib/benchmark-directory';
import { getAllApiRefSlugs } from '@/lib/api-reference-directory';
import { getAllHarnessSlugs } from '@/lib/harness-directory';
import { getActiveCategoryIds } from '@/data/gear/products';
import { AI_COMPANIES } from '@/data/ai-companies/companies';
import { CRAWLER_DOMAINS } from '@/data/ai-crawler-access/domains';

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://tensorfeed.ai';
  const now = new Date();

  // Individual model pages (generated from model directory)
  const modelPages: MetadataRoute.Sitemap = getAllModelSlugs().map(slug => ({
    url: `${baseUrl}/models/${slug}`,
    lastModified: now,
    changeFrequency: 'weekly' as const,
    priority: 0.7,
  }));

  // Comparison pages (high-intent "vs" search queries)
  const comparisonPages: MetadataRoute.Sitemap = getAllComparisonSlugs().map(slug => ({
    url: `${baseUrl}/compare/${slug}`,
    lastModified: now,
    changeFrequency: 'weekly' as const,
    priority: 0.7,
  }));

  // Per-benchmark leaderboard pages (high-intent "best AI model on X" queries)
  const benchmarkPages: MetadataRoute.Sitemap = getAllBenchmarkSlugs().map(slug => ({
    url: `${baseUrl}/benchmarks/${slug}`,
    lastModified: now,
    changeFrequency: 'weekly' as const,
    priority: 0.75,
  }));

  // Per-endpoint API reference pages (branded "tensorfeed X api" queries)
  const apiRefPages: MetadataRoute.Sitemap = getAllApiRefSlugs().map(slug => ({
    url: `${baseUrl}/api-reference/${slug}`,
    lastModified: now,
    changeFrequency: 'weekly' as const,
    priority: 0.75,
  }));

  // Provider hub pages
  const providerPages: MetadataRoute.Sitemap = getAllProviderSlugs().map(slug => ({
    url: `${baseUrl}/providers/${slug}`,
    lastModified: now,
    changeFrequency: 'weekly' as const,
    priority: 0.7,
  }));

  // Per-harness detail pages (Claude Code, Cursor, Codex CLI, Aider, etc)
  const harnessPages: MetadataRoute.Sitemap = getAllHarnessSlugs().map(slug => ({
    url: `${baseUrl}/harnesses/${slug}`,
    lastModified: now,
    changeFrequency: 'weekly' as const,
    priority: 0.75,
  }));

  // Gear category subpages (only categories with products are generated)
  const gearCategoryPages: MetadataRoute.Sitemap = getActiveCategoryIds().map(
    slug => ({
      url: `${baseUrl}/gear/${slug}`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.75,
    })
  );

  // Per-domain AI crawler access pages (one static page per tracked domain)
  const crawlerDomainPages: MetadataRoute.Sitemap = CRAWLER_DOMAINS.map(d => ({
    url: `${baseUrl}/ai-crawler-access/${d.domain}`,
    lastModified: now,
    changeFrequency: 'weekly' as const,
    priority: 0.6,
  }));

  return [
    // Core pages (update frequently)
    { url: baseUrl, lastModified: now, changeFrequency: 'always', priority: 1.0 },
    { url: `${baseUrl}/status`, lastModified: now, changeFrequency: 'always', priority: 0.9 },
    { url: `${baseUrl}/leaderboard`, lastModified: now, changeFrequency: 'always', priority: 0.9 },
    { url: `${baseUrl}/badges`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/embed`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    // Per-provider uptime trend pages (one per monitored provider)
    { url: `${baseUrl}/uptime/claude`, lastModified: now, changeFrequency: 'always', priority: 0.85 },
    { url: `${baseUrl}/uptime/openai`, lastModified: now, changeFrequency: 'always', priority: 0.85 },
    { url: `${baseUrl}/uptime/gemini`, lastModified: now, changeFrequency: 'always', priority: 0.85 },
    { url: `${baseUrl}/uptime/groq`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/uptime/bedrock`, lastModified: now, changeFrequency: 'always', priority: 0.85 },
    { url: `${baseUrl}/uptime/azure`, lastModified: now, changeFrequency: 'always', priority: 0.85 },
    { url: `${baseUrl}/uptime/deepseek`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/uptime/together`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/uptime/fireworks`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/uptime/openrouter`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/uptime/perplexity`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/uptime/copilot`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/uptime/huggingface`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/uptime/replicate`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/uptime/cohere`, lastModified: now, changeFrequency: 'always', priority: 0.75 },
    { url: `${baseUrl}/uptime/mistral`, lastModified: now, changeFrequency: 'always', priority: 0.75 },
    { url: `${baseUrl}/uptime/elevenlabs`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/uptime/stability`, lastModified: now, changeFrequency: 'always', priority: 0.75 },
    { url: `${baseUrl}/uptime/runway`, lastModified: now, changeFrequency: 'always', priority: 0.75 },
    { url: `${baseUrl}/uptime/luma`, lastModified: now, changeFrequency: 'always', priority: 0.75 },
    { url: `${baseUrl}/today`, lastModified: now, changeFrequency: 'always', priority: 0.9 },
    { url: `${baseUrl}/live`, lastModified: now, changeFrequency: 'always', priority: 0.9 },
    { url: `${baseUrl}/models`, lastModified: now, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${baseUrl}/intelligence`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    ...modelPages,
    ...comparisonPages,
    ...providerPages,
    ...benchmarkPages,
    ...harnessPages,
    ...apiRefPages,
    { url: `${baseUrl}/api-reference`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/catalogs`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/agents`, lastModified: now, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${baseUrl}/agents/leaderboard`, lastModified: now, changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/agents/claim`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    // Self-directory pages (/agents/hireable, /agents/profile) remain
    // parked 2026-05-13; reachable by direct URL but not promoted.
    { url: `${baseUrl}/research`, lastModified: now, changeFrequency: 'daily', priority: 0.9 },
    { url: `${baseUrl}/research/papers`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/research/state-of-ai-agent-data-2026`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/research/milestones`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/research/authors`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/research/citation-velocity`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/research/conference-acceptances`, lastModified: now, changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/research/nlp-proceedings`, lastModified: now, changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/research/lab-blogs`, lastModified: now, changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/research/topics`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    // raw, unverified arXiv firehose; honestly labeled, not a quality product, not promoted.
    { url: `${baseUrl}/research/firehose`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/podcasts`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },

    // "Is X Down" status pages (high-traffic search queries)
    { url: `${baseUrl}/is-claude-down`, lastModified: now, changeFrequency: 'always', priority: 0.9 },
    { url: `${baseUrl}/is-chatgpt-down`, lastModified: now, changeFrequency: 'always', priority: 0.9 },
    { url: `${baseUrl}/is-gemini-down`, lastModified: now, changeFrequency: 'always', priority: 0.9 },
    { url: `${baseUrl}/is-perplexity-down`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/is-copilot-down`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/is-midjourney-down`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/is-huggingface-down`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/is-mistral-down`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/is-replicate-down`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/is-cohere-down`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/is-bedrock-down`, lastModified: now, changeFrequency: 'always', priority: 0.9 },
    { url: `${baseUrl}/is-azure-openai-down`, lastModified: now, changeFrequency: 'always', priority: 0.9 },
    { url: `${baseUrl}/is-deepseek-down`, lastModified: now, changeFrequency: 'always', priority: 0.85 },
    { url: `${baseUrl}/is-groq-down`, lastModified: now, changeFrequency: 'always', priority: 0.85 },
    { url: `${baseUrl}/is-together-down`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/is-fireworks-down`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/is-openrouter-down`, lastModified: now, changeFrequency: 'always', priority: 0.85 },
    { url: `${baseUrl}/is-elevenlabs-down`, lastModified: now, changeFrequency: 'always', priority: 0.85 },
    { url: `${baseUrl}/is-stability-ai-down`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/is-runway-down`, lastModified: now, changeFrequency: 'always', priority: 0.8 },
    { url: `${baseUrl}/is-luma-down`, lastModified: now, changeFrequency: 'always', priority: 0.8 },

    // Pillar/guide pages
    { url: `${baseUrl}/what-is-ai`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/best-ai-tools`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/best-ai-chatbots`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/ai-api-pricing-guide`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/what-are-ai-agents`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/best-open-source-llms`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/agi-asi`, lastModified: now, changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/model-wars`, lastModified: now, changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/claude-md-guide`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/claude-md-examples`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/claude-md-generator`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },

    // Tools & features
    { url: `${baseUrl}/compare`, lastModified: now, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${baseUrl}/benchmarks`, lastModified: now, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${baseUrl}/harnesses`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/attention`, lastModified: now, changeFrequency: 'always', priority: 0.85 },
    { url: `${baseUrl}/playground`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/embeddings`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/inference-providers`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/multimodal`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/vector-dbs`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/usage-rankings`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/frameworks`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/benchmark-registry`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/open-weights`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/ai-hardware`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/mcp-servers`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/training-datasets`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/embodied-ai`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/ai-lawsuits`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/x402-adopters`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/agent-apis`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/training-runs`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/fine-tuning`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/specialized-models`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/model-cards`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/voice-leaderboards`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/marketplaces`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/public-leaderboards`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/funding`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/funding/portfolio`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/funding/federal`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/procurement`, lastModified: now, changeFrequency: 'daily', priority: 0.75 },
    { url: `${baseUrl}/substrate`, lastModified: now, changeFrequency: 'daily', priority: 0.7 },
    { url: `${baseUrl}/export-controls`, lastModified: now, changeFrequency: 'daily', priority: 0.7 },
    { url: `${baseUrl}/ai-infrastructure`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/ai-stocks`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    ...AI_COMPANIES.map((company) => ({
      url: `${baseUrl}/ai-stocks/${company.ticker.toLowerCase()}`,
      lastModified: now,
      changeFrequency: 'daily' as const,
      priority: 0.85,
    })),
    { url: `${baseUrl}/a2a-x402`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/hyperliquid`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/cve-watch`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/oss-tools`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/ai-policy`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/conferences`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/compute-providers`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/timeline`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/tools/cost-calculator`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/tools/trending`, lastModified: now, changeFrequency: 'daily', priority: 0.7 },
    { url: `${baseUrl}/gpu-pricing`, lastModified: now, changeFrequency: 'always', priority: 0.85 },
    { url: `${baseUrl}/sports`, lastModified: now, changeFrequency: 'daily', priority: 0.7 },
    { url: `${baseUrl}/sports/nfl`, lastModified: now, changeFrequency: 'hourly', priority: 0.8 },
    { url: `${baseUrl}/sports/mlb`, lastModified: now, changeFrequency: 'hourly', priority: 0.8 },
    { url: `${baseUrl}/economy`, lastModified: now, changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/research/institutions`, lastModified: now, changeFrequency: 'daily', priority: 0.8 },
    { url: `${baseUrl}/packages`, lastModified: now, changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/policy`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/alerts`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/incidents`, lastModified: now, changeFrequency: 'always', priority: 0.8 },

    // Developer, editorial, changelog
    { url: `${baseUrl}/developers`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/developers/agent-payments`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/developers/frameworks`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/x402`, lastModified: now, changeFrequency: 'daily', priority: 0.95 },
    { url: `${baseUrl}/x402/verified`, lastModified: now, changeFrequency: 'daily', priority: 0.9 },
    { url: `${baseUrl}/mcp`, lastModified: now, changeFrequency: 'daily', priority: 0.95 },
    { url: `${baseUrl}/x402-registry`, lastModified: now, changeFrequency: 'daily', priority: 0.9 },
    { url: `${baseUrl}/agent-fair-trade`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/afta-network`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/afta-certified`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/pricing/packs`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/data-licensing`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/services`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/mcp/pro`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/agent-provisioning`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/verified-feed`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/security/corroborated`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${baseUrl}/changelog`, lastModified: now, changeFrequency: 'weekly', priority: 0.6 },
    { url: `${baseUrl}/verdicts`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/verdicts/best-value-coding-model`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/verdicts/benchmarks-to-distrust`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/verdicts/compute-growth-slowdown`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/verdicts/trust-ai-found-cves`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/verdicts/frontier-premium-worth-it`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/originals`, lastModified: now, changeFrequency: 'weekly', priority: 0.7 },
    { url: `${baseUrl}/originals/gpt-56-sol-public-sonnet-5-monopoly-ends`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/microsoft-mai-office-swap-anthropic-ceiling`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/openai-42-billion-federal-gate-price-tag`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/un-geneva-dialogue-scientific-panel-alignment-footnote`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/hyperscaler-fde-turn-microsoft-frontier-aws-billion`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/h1-2026-vc-concentration-two-labs`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/un-ai-commission-geneva-third-rail-governance`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/first-macro-ai-print-june-jobs-report`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/cloudflare-monetization-gateway-x402-mcp-edge`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/claude-science-harness-is-the-product`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/claude-sonnet-5-only-frontier-available-federal-gate`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/copilot-first-cycle-bill-shock-developer-tokenmaxx`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/meituan-longcat-2-owl-alpha-openrouter`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/qwen-agentworld-mcp-simulator-open-frontier`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/deepmind-talent-exodus-gemini-pro-slip`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/anthropic-alibaba-distillation-senate-banking-sanctions`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/tokenmaxxing-cliff-ipo-math`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/inference-money-vs-ai-chip-stocks`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/white-house-gpt-56-stagger-federal-gate-bilateral`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/openai-jalapeno-custom-silicon-loop-closed`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/openai-samsung-electronics-dx-chaebol-dual-stack`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/reflection-ai-6b-colossus-open-frontier-compute`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/china-295b-state-ai-grid-sovereign-rail`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/shazeer-google-openai-acqui-hire-cliff`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/openai-partner-network-150m-channel-moat`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/openai-frontier-model-science-loop`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/aws-waf-bot-monetization-x402-rails`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/anthropic-seoul-chaebol-sovereignty-playbook`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/spacex-cursor-acquisition-coding-consolidation`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/white-house-jailbreak-proof-fable-5-mandate`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/amazon-pulled-fable-5-hyperscaler-conflict`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/anthropic-off-switch-brussels-g7-evian`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/glm-5-2-open-frontier-export-letter`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/anthropic-overtakes-openai-enterprise-adoption-ramp`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/fable-5-mythos-5-export-control-suspension`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/coinbase-agents-x402-closed-loop`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/openai-oracle-credits-frontier-procurement`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/mastercard-agent-pay-machines-x402-trust-layer`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/claude-fable-5-mythos-5-split-frontier`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/anthropic-maia-200-fourth-chip-inference`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/apple-gemini-siri-extensions-wwdc-2026`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/ai-capex-bubble-debate-scoreboard`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/government-equity-stakes-ai-labs-ipo-window`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/chatgpt-dreaming-v3-memory-default`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/great-american-ai-act-preemption`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/spacex-ipo-anthropic-colossus-compute`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/deepseek-maiden-funding-round-59-billion`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/card-networks-base-settlement-agents`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/microsoft-mai-models-openai-independence`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/nvidia-rtx-spark-edge-agents`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/x402-multi-rail-fireblocks-allunity`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/anthropic-confidential-s1-ipo`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/california-30-ai-bills-crossover-july-sprint`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/x402-batch-settlement-base-mcp-distribution-layer`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/trump-pulled-federal-ai-review-order`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/openai-frontier-governance-framework-compliance-era`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/tavily-x402-search-discovery-layer-gap`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/opus-4-8-workflow-orchestration-primitive`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/robinhood-agentic-trading-mcp-brokerage-account`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/four-frontier-labs-acqui-hire-consolidation`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/pope-leo-magnifica-humanitas-anthropic-olah`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/starlette-badhost-critical-cve-agent-stack-audit`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/altman-amodei-walk-back-jobs-apocalypse-ipo-pivot`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/anthropic-glasswing-update-mythos-public-release`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/agent-commerce-fee-floor-spacex-memo`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/agent-native-browsers-firefox-fork-runtime-shift`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/chatbot-personality-exploits-prompt-injection-grows-up`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/xai-2-8b-gas-turbines-energy-bottleneck`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/openai-erdos-unit-distance-disproof`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/openai-ipo-filing-anthropic-first-profit`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/ai-status-extension-live`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/anthropic-karpathy-four-moves-one-week`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/anthropic-stainless-sdk-supply-chain`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/openai-chatgpt-bank-access-agent-trust-gap`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/mistral-europe-ai-sovereignty-two-year-clock`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/codex-bleed-anthropic-three-interventions`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/cerebras-95-billion-ipo-inference-bet`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/wafer-scale-vs-gpu-what-cerebras-sells`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/cerebras-g42-cfius-national-security-tax`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/live-ai-status-widget`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/ai-week-may-15-2026`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/aws-ships-hosted-mcp-server`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/google-a2a-x402-payments-extension`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/cve-data-layer-matters-now`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/agentic-usdc-pay-and-trade-converge`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/apple-20-day-window-io-wwdc`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/google-gemini-intelligence-android-platform-shift`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/openai-daybreak-cyber-counter-mythos`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/google-io-2026-gemini-4-stakes`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/nvidia-40b-equity-customer-investor-loop`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/anthropic-200b-google-tpu-math`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/ai-buildout-explained`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/ai-nuclear-restart-thesis`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/ai-compute-orbital-thesis`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/ferc-ai-data-center-bypass-watch`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/openai-gpt-realtime-2-voice-stack`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/anthropic-spacexai-colossus-orbital`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/verified-feed-trust-layer`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/ai-cyber-tier-data-layer`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/ai-week-may-8-2026`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/aws-x402-coinbase-agent-payments`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/x402-verifier-mcp-launch`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/verify`, lastModified: now, changeFrequency: 'daily', priority: 0.95 },
    { url: `${baseUrl}/mcp/activity`, lastModified: now, changeFrequency: 'hourly', priority: 0.9 },
    { url: `${baseUrl}/x402/health`, lastModified: now, changeFrequency: 'hourly', priority: 0.9 },
    { url: `${baseUrl}/originals/anthropic-dreaming-managed-agents`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/apple-intelligence-extensions-ios-27`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/one-day-eight-free-apis`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/audited-our-paid-api-killed-two-endpoints`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/sap-prior-labs-europe-frontier-lab`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/originals/claude-opus-4-7-release`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/originals/llms-txt-every-developer`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/ai-pricing-floor`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/why-we-built-tensorfeed`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/openai-killed-sora`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/mcp-97-million-installs`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/claude-code-leak`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/ai-service-outages-month`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/ai-api-pricing-war-2026`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/open-source-llms-closing-gap`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/rise-of-agentic-ai`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/claude-mythos-not-afraid`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/building-for-ai-agents`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/ai-adoption-faster-than-internet`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/4chan-discovered-chain-of-thought`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/frontier-model-forum-vs-china`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/claude-mythos-ai-security`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/google-notebooklm-gemini`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/stanford-ai-index-2026`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/claude-vs-gpt-vs-gemini`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/state-of-ai-apis-2026`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/gpt-5-5-openai-flagship`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/claude-design-anthropic`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/ai-week-april-24-2026`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/google-anthropic-40b-compute`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/originals/deepseek-v4-open-source-frontier`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/originals/ai-money-gap-pwc`, lastModified: now, changeFrequency: 'monthly', priority: 0.6 },
    { url: `${baseUrl}/originals/anthropic-project-deal-agent-marketplace`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/originals/openai-workspace-agents-chatgpt-enterprise`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/originals/alibaba-happy-horse-video-crown`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/originals/microsoft-openai-partnership-reset`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/originals/validating-agent-payments-mainnet`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/originals/15-paid-endpoints-24-hours`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/originals/why-usdc-over-stripe`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/originals/mcp-server-fifty-line-file`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/originals/kv-ops-budget-edge-architecture`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/originals/publishing-bot-traffic`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/originals/ai-talent-war-billion-dollar-engineers`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/originals/openai-aws-bedrock-24-hours`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${baseUrl}/originals/measuring-llm-api-latency-from-the-edge`, lastModified: now, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${baseUrl}/originals/guard-act-senate-judiciary-22-0`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/harness-gap-not-the-model`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/palo-alto-portkey-mcp-gateway`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/stripe-link-vs-usdc-agent-payments`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/pentagon-blacklists-anthropic-defense-deals`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/ai-status-monitoring-real-talk`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/agents-md-new-robots-txt`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/ai-inference-floor-may-2026`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/cloudflare-stripe-agent-provisioning-protocol`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/mistral-medium-3-5-open-weights-frontier-coder`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/afta-is-bilateral-both-sides-win`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/anthropic-900-billion-valuation-tops-openai`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/anthropic-finance-agents-wall-street`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/coinbase-armstrong-14-percent-ai-native-pivot`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },
    { url: `${baseUrl}/originals/we-chose-usdc-on-base-for-afta`, lastModified: now, changeFrequency: 'weekly', priority: 0.95 },

    // Whitepaper (canonical AFTA spec document)
    { url: `${baseUrl}/whitepaper`, lastModified: now, changeFrequency: 'monthly', priority: 0.95 },

    // Model lifecycle (free data feed, agent-relevant)
    { url: `${baseUrl}/model-deprecations`, lastModified: now, changeFrequency: 'weekly', priority: 0.85 },

    // Agent-acquisition surface
    { url: `${baseUrl}/for-ai-agents`, lastModified: now, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${baseUrl}/datasets`, lastModified: now, changeFrequency: 'daily', priority: 0.9 },
    { url: `${baseUrl}/agent-traffic`, lastModified: now, changeFrequency: 'always', priority: 0.85 },
    { url: `${baseUrl}/ai-crawler-access`, lastModified: now, changeFrequency: 'daily', priority: 0.85 },
    { url: `${baseUrl}/agent-ready`, lastModified: now, changeFrequency: 'daily', priority: 0.85 },
    ...crawlerDomainPages,
    { url: `${baseUrl}/glossary`, lastModified: now, changeFrequency: 'monthly', priority: 0.7 },
    { url: `${baseUrl}/glossary/x402`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/glossary/mcp`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },
    { url: `${baseUrl}/glossary/agent-payments`, lastModified: now, changeFrequency: 'monthly', priority: 0.75 },

    // Use-case landing pages (per agent persona)
    { url: `${baseUrl}/use-cases`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/use-cases/coding-agents`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/use-cases/research-agents`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/use-cases/api-cost-monitoring`, lastModified: now, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${baseUrl}/use-cases/agent-payments`, lastModified: now, changeFrequency: 'monthly', priority: 0.85 },

    // Info pages
    { url: `${baseUrl}/about`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/authors`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/authors/adrian-vale`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/authors/kira-nolan`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/authors/marcus-chen`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/editorial-policy`, lastModified: now, changeFrequency: 'monthly', priority: 0.5 },
    { url: `${baseUrl}/privacy`, lastModified: now, changeFrequency: 'monthly', priority: 0.3 },
    { url: `${baseUrl}/terms`, lastModified: now, changeFrequency: 'monthly', priority: 0.3 },
    { url: `${baseUrl}/security`, lastModified: now, changeFrequency: 'monthly', priority: 0.3 },
    { url: `${baseUrl}/contact`, lastModified: now, changeFrequency: 'monthly', priority: 0.4 },
    // Gear (curated AI-relevant consumer hardware, refreshed weekly)
    { url: `${baseUrl}/gear`, lastModified: now, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${baseUrl}/gear/policy`, lastModified: now, changeFrequency: 'yearly', priority: 0.3 },
    ...gearCategoryPages,
  ];
}
