// scripts/generate-crawler-domains.ts
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const SRC = 'worker/src/ai-crawler-access-seeds.ts';
const OUT = 'src/data/ai-crawler-access/domains.ts';

const src = readFileSync(SRC, 'utf8');
const re = /\{ domain: '([^']+)', sector: '([^']+)' \}/g;
const rows: Array<{ domain: string; sector: string }> = [];
let m: RegExpExecArray | null;
while ((m = re.exec(src)) !== null) rows.push({ domain: m[1], sector: m[2] });
if (rows.length === 0) throw new Error('generate-crawler-domains: no domains parsed');

const body =
  '// GENERATED by scripts/generate-crawler-domains.ts from worker/src/ai-crawler-access-seeds.ts. Do not edit by hand.\n' +
  'export interface CrawlerDomain { domain: string; sector: string; }\n' +
  'export const CRAWLER_DOMAINS: CrawlerDomain[] = [\n' +
  rows.map((r) => `  { domain: '${r.domain}', sector: '${r.sector}' },`).join('\n') +
  '\n];\n' +
  'export const CRAWLER_DOMAIN_SET = new Set(CRAWLER_DOMAINS.map((d) => d.domain));\n';

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, body, 'utf8');
console.log(`generate-crawler-domains: wrote ${rows.length} domains to ${OUT}`);
