name = "tensorfeed-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = [
  "*/10 * * * *",
  "*/2 * * * *",
  "0 * * * *",
]

[[kv_namespaces]]
binding = "TENSORFEED_NEWS"
id = ""
preview_id = ""

[[kv_namespaces]]
binding = "TENSORFEED_STATUS"
id = ""
preview_id = ""

[[kv_namespaces]]
binding = "TENSORFEED_CACHE"
id = ""
preview_id = ""

[vars]
ENVIRONMENT = "production"
SITE_URL = "https://tensorfeed.ai"
